- README.md
> 🎉 add Read me 파일 생성

- AbyssDiverUnderWorld.uproject
- Source/AbyssDiverUnderWorld/AbyssDiverUnderWorld.cpp
- Source/AbyssDiverUnderWorld/AbyssDiverUnderWorld.h
---
- 커스텀 로그 기능 구현
- 네트워크 포함된 로그 LOGN
- UObject 상속받은 클래스에서 사용하는 로그 LOG
---
---
---
> [Add] 커스텀 로그 기능 구현

- AbyssDiverUnderWorld.uproject
- Content/_AbyssDiver/Blueprints/Boss/BB_Boss.uasset
- Content/_AbyssDiver/Blueprints/Boss/BP_Kraken.uasset
- Content/_AbyssDiver/Blueprints/Boss/BT_Boss.uasset
- Content/_AbyssDiver/Blueprints/Boss/Kraken/BP_Kraken.uasset
- Content/_AbyssDiver/Blueprints/Boss/Kraken/BP_KrakenAIController.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/KDY.umap
- Source/AbyssDiverUnderWorld/AbyssDiverUnderWorld.Build.cs
- Source/AbyssDiverUnderWorld/Boss/Boss.cpp
- Source/AbyssDiverUnderWorld/Boss/Boss.h
- Source/AbyssDiverUnderWorld/Boss/BossAIController.cpp
- Source/AbyssDiverUnderWorld/Boss/BossAIController.h
- Source/AbyssDiverUnderWorld/Boss/Kraken/Kraken.cpp
- Source/AbyssDiverUnderWorld/Boss/Kraken/Kraken.h
- Source/AbyssDiverUnderWorld/Boss/Kraken/KrakenAIController.cpp
- Source/AbyssDiverUnderWorld/Boss/Kraken/KrakenAIController.h
---
- Boss, BossAiController 클래스 기초 구현
- Boss 를 상속받는 Kraken | BossAIController를 상속받는 KrakenAiController 기초 구현
- Kraken Blueprint 셋팅
- 로그 출력으로 정상 작동 확인
---
---
---
> [Add] Kraken 기초 구현

- Content/_AbyssDiver/DataTable/DT_DropEntry.uasset
- Source/AbyssDiverUnderWorld/Container/FStructContainer.cpp
- Source/AbyssDiverUnderWorld/Container/FStructContainer.h
- Source/AbyssDiverUnderWorld/Interactable/Item/ADItemBase.cpp
- Source/AbyssDiverUnderWorld/Interactable/Item/ADItemBase.h
- Source/AbyssDiverUnderWorld/Interactable/Item/ADOreRock.cpp
- Source/AbyssDiverUnderWorld/Interactable/Item/ADOreRock.h
- Source/AbyssDiverUnderWorld/Interface/IADInteractable.cpp
- Source/AbyssDiverUnderWorld/Interface/IADInteractable.h
---
AADItemBase 클래스
> Interact, HandlePickup 기능 구현
> 상호작용 시 아이템 획득 로직 추가
AADOreRock 클래스
> 채굴 상호작용 시 드롭 테이블 기반 아이템 생성 기능 구현
> 드롭 아이템의 Mass 및 수량이 FDropEntry 기준 랜덤 생성되도록 구현 (DT_DropEntry 추가)
IADInteractable
> Interact 함수 선언 (상호작용할 수 있는 모든 클래스가 구현)
FStructContainer
> 유용한 구조체를 넣어둘 컨테이너 추가. (FItemData를 먼저 넣어두었습니다.)
---
---
- 자료형을 적절하게 썼는지 확인 부탁드립니다.
---
> 🎉 add ADItemBase, IADInteractable, DT_DropEntry

- Content/_AbyssDiver/Blueprints/Boss/BT_Boss.uasset
- Content/_AbyssDiver/Blueprints/Boss/E_BossState.uasset
- Content/_AbyssDiver/Blueprints/Boss/Kraken/BP_Kraken.uasset
- Content/_AbyssDiver/Blueprints/Boss/Kraken/BP_KrakenAIController.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/KDY.umap
- Source/AbyssDiverUnderWorld/Boss/Boss.cpp
- Source/AbyssDiverUnderWorld/Boss/Boss.h
- Source/AbyssDiverUnderWorld/Boss/BossAIController.cpp
- Source/AbyssDiverUnderWorld/Boss/BossAIController.h
- Source/AbyssDiverUnderWorld/Boss/EBossState.h
- Source/AbyssDiverUnderWorld/Boss/Kraken/Kraken.cpp
- Source/AbyssDiverUnderWorld/Boss/Kraken/Kraken.h
- Source/AbyssDiverUnderWorld/Boss/Kraken/KrakenAIController.cpp
- Source/AbyssDiverUnderWorld/Boss/Task/BTTask_BossChasing.cpp
- Source/AbyssDiverUnderWorld/Boss/Task/BTTask_BossChasing.h
- Source/AbyssDiverUnderWorld/Boss/Task/BTTask_BossInvestigate.cpp
- Source/AbyssDiverUnderWorld/Boss/Task/BTTask_BossInvestigate.h
- Source/AbyssDiverUnderWorld/Boss/Task/BTTask_BossMove.cpp
- Source/AbyssDiverUnderWorld/Boss/Task/BTTask_BossMove.h
- Source/AbyssDiverUnderWorld/Boss/Task/BTTask_ChangeBossState.cpp
---
- 크라켄의 시야각 90도 이내 + 7000미터 이내인 경우 추적 상태로 전이
- 시야각에서 플레이어가 사라진 경우 탐지 상태로 전이
---
---
---
> [Update] 보스 추적, 탐지 상태 구현

- Content/_AbyssDiver/Blueprints/Interactables/Item/BP_ADOreRock.uasset
- Content/_AbyssDiver/Blueprints/Interactables/Item/Minerals/BP_Chromite.uasset
- Content/_AbyssDiver/Blueprints/Interactables/Item/Minerals/BP_CobaltShell.uasset
- Content/_AbyssDiver/Blueprints/Interactables/Item/Minerals/BP_LostRune.uasset
- Content/_AbyssDiver/Blueprints/Interactables/Item/Minerals/BP_MagneticCrystal.uasset
- Content/_AbyssDiver/Blueprints/Interactables/Item/Minerals/BP_QuantumCore.uasset
- Content/_AbyssDiver/DataTable/DT_DropEntry.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/CWS.umap
- Source/AbyssDiverUnderWorld/AbyssDiverUnderWorld.Build.cs
- Source/AbyssDiverUnderWorld/Container/FStructContainer.h
- Source/AbyssDiverUnderWorld/Interactable/Item/ADExchangeableItem.cpp
- Source/AbyssDiverUnderWorld/Interactable/Item/ADExchangeableItem.h
- Source/AbyssDiverUnderWorld/Interactable/Item/ADItemBase.cpp
- Source/AbyssDiverUnderWorld/Interactable/Item/ADItemBase.h
- Source/AbyssDiverUnderWorld/Interactable/Item/ADOreRock.cpp
- Source/AbyssDiverUnderWorld/Interactable/Item/ADOreRock.h
- Source/AbyssDiverUnderWorld/Interface/IADInteractable.h
---
ADExchangeableItem 클래스 추가
> AADItemBase 상속 기반으로 Mass, ValuePerUnit, TotalPrice 계산 로직 구현
> Interact → HandlePickup 흐름에 가격 계산(CalculateTotalPrice) 및 인벤토리 처리 확장
AADOreRock 드롭 로직 개선
> Crash 문제 해결을 위해 FStreamableManager 멤버 제거 후, 전역 UAssetManager::Get().GetStreamableManager()로 비동기 로드 처리
> SpawnDrops SampleDropMass 함수로 무게 샘플링 로직 분리
> Power-Law 샘플링 사용: MassBiasExponent에 따른 분포 조정 (높은 무게는 낮은 확률로 드랍)
> ProjectileMovementComponent 활성화해 공중 드롭 및 파편 튕김 효과 구현
나이아가라 이펙트 통합
> PickAxeImpactFX, RockFragmentsFX Niagara 시스템 프로퍼티로 추가
> HandleMineRequest 분기 처리로 채굴 중·파쇄 시 이펙트 재생
> Build.cs에 "Niagara" 모듈 추가
블루프린트 래핑
> BP_ExchangeableItem 및 BP_OreRock 블루프린트 서브클래스 생성
> 에디터에서 메시, MassBiasExponent, 이펙트 자산 등 프로퍼티 조정 후 DataTable에 등록
---
---
---
> 🎉 add Item BP, ✨ update Item Logic  ✨ update Build.cs

- Content/SciFi_Octopus/Animations/AM_Kraken_Roar.uasset
- Content/_AbyssDiver/Blueprints/Boss/BT_Boss.uasset
- Content/_AbyssDiver/Blueprints/Boss/E_BossState.uasset
- Content/_AbyssDiver/Blueprints/Boss/Kraken/BP_Kraken.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/KDY.umap
- Source/AbyssDiverUnderWorld/Boss/AnimNotify/AnimNotify_ChangeBossState.cpp
- Source/AbyssDiverUnderWorld/Boss/AnimNotify/AnimNotify_ChangeBossState.h
- Source/AbyssDiverUnderWorld/Boss/Boss.cpp
- Source/AbyssDiverUnderWorld/Boss/Boss.h
- Source/AbyssDiverUnderWorld/Boss/BossAIController.cpp
- Source/AbyssDiverUnderWorld/Boss/BossAIController.h
- Source/AbyssDiverUnderWorld/Boss/EBossState.h
- Source/AbyssDiverUnderWorld/Boss/Task/BTTask_BossChasing.cpp
- Source/AbyssDiverUnderWorld/Boss/Task/BTTask_BossInvestigate.cpp
- Source/AbyssDiverUnderWorld/Boss/Task/BTTask_Detected.cpp
- Source/AbyssDiverUnderWorld/Boss/Task/BTTask_Detected.h
---
- 최초로 플레이어를 감지할 경우 Roar 애니메이션 재생 후 Chase 상태로 전이
- AnimNotify로 보스의 상태를 변환할 수 있도록 구현
- Idle, Move 상태의 경우 시야각이 90도로 제한되지만, Chase 상태의 경우 시야각이 150도로 넓어짐
---
---
---
> [Update] 보스 감지 상태 구현

- Content/_AbyssDiver/Blueprints/Character/BP_UnderwaterCharacter.uasset
- Content/_AbyssDiver/Input/IA_Plyaer/IA_Aim.uasset
- Content/_AbyssDiver/Input/IA_Plyaer/IA_Down.uasset
- Content/_AbyssDiver/Input/IA_Plyaer/IA_Fire.uasset
- Content/_AbyssDiver/Input/IA_Plyaer/IA_Interaction.uasset
- Content/_AbyssDiver/Input/IA_Plyaer/IA_Inventory.uasset
- Content/_AbyssDiver/Input/IA_Plyaer/IA_Light.uasset
- Content/_AbyssDiver/Input/IA_Plyaer/IA_Look.uasset
- Content/_AbyssDiver/Input/IA_Plyaer/IA_Move.uasset
- Content/_AbyssDiver/Input/IA_Plyaer/IA_Radar.uasset
- Content/_AbyssDiver/Input/IA_Plyaer/IA_Rise.uasset
- Content/_AbyssDiver/Input/IA_Plyaer/IA_SelectInventorySlot1.uasset
- Content/_AbyssDiver/Input/IA_Plyaer/IA_SelectInventorySlot2.uasset
- Content/_AbyssDiver/Input/IA_Plyaer/IA_SelectInventorySlot3.uasset
- Content/_AbyssDiver/Input/IA_Plyaer/IA_Up.uasset
- Content/_AbyssDiver/Input/IMC_Player.uasset
- Source/AbyssDiverUnderWorld/Character/UnderwaterCharacter.cpp
- Source/AbyssDiverUnderWorld/Character/UnderwaterCharacter.h
- Source/AbyssDiverUnderWorld/Framework/ADPlayerController.cpp
- Source/AbyssDiverUnderWorld/Framework/ADPlayerController.h
---
- 캐릭터가 WASD 키로 움직이도록 구현
- W : Forward
- S : Backward
- A : Left Straf
- D : Right Straf
---
Player Controller의 BP 부분은 충돌 우려가 있기 때문에 현재 작성하지 않았습니다. 추후 담당자와 연락 후 조율하겠습니다.
생성자에서 기본 IMC를 지정했기 때문에 현재로서는 ADPlyaerController C++ Class를 지정해주시면 될 것 같습니다.
---
---
> Add: Character Input Binding, Camera, Move

- Content/SciFi_Octopus/Animations/AM_Kraken_Bite.uasset
- Content/SciFi_Octopus/Animations/AM_Kraken_Laser.uasset
- Content/SciFi_Octopus/Animations/AM_Kraken_TakeDown.uasset
- Content/SciFi_Octopus/Animations/AM_Kraken_Wield.uasset
- Content/SciFi_Octopus/Animations/Anim_SciFi_Octopus_Attack4.uasset
- Content/SciFi_Octopus/Animations/Anim_SciFi_Octopus_Attack5.uasset
- Content/_AbyssDiver/Blueprints/ABP/Boss/Kraken/ABP_Kraken.uasset
- Content/_AbyssDiver/Blueprints/Boss/BT_Boss.uasset
- Content/_AbyssDiver/Blueprints/Boss/Kraken/BP_Kraken.uasset
- Content/_AbyssDiver/Blueprints/Boss/Kraken/BP_KrakenAIController.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/KDY.umap
- Source/AbyssDiverUnderWorld/Boss/Boss.cpp
- Source/AbyssDiverUnderWorld/Boss/Boss.h
- Source/AbyssDiverUnderWorld/Boss/Kraken/Kraken.cpp
- Source/AbyssDiverUnderWorld/Boss/Task/BTTask_BossAttack.cpp
- Source/AbyssDiverUnderWorld/Boss/Task/BTTask_BossAttack.h
---
- 보스 공격 로직 : Chase 상태에서 일정반경 내에 플레이어가 들어온 경우 Attack 상태로 전이
---
---
---
> [Add, Update] Kraken 공격 상태 구현

- Content/SciFi_Octopus/Animations/AM_Kraken_Death.uasset
- Content/SciFi_Octopus/Animations/Anim_SciFi_Octopus_Death1.uasset
- Content/_AbyssDiver/Blueprints/ABP/Boss/Kraken/ABP_Kraken.uasset
- Content/_AbyssDiver/Blueprints/Boss/BT_Boss.uasset
- Content/_AbyssDiver/Blueprints/Boss/E_BossState.uasset
- Content/_AbyssDiver/Blueprints/Boss/Kraken/BP_Kraken.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/KDY.umap
- Source/AbyssDiverUnderWorld/Boss/Boss.cpp
- Source/AbyssDiverUnderWorld/Boss/Boss.h
- Source/AbyssDiverUnderWorld/Boss/BossAIController.cpp
- Source/AbyssDiverUnderWorld/Boss/BossAIController.h
- Source/AbyssDiverUnderWorld/Boss/EBossState.h
- Source/AbyssDiverUnderWorld/Boss/Task/BTTask_BossChasing.cpp
---
- 크라켄 체력이 0 이하로 떨어지는 경우 사망 상태로 전이
---
---
---
> [Update] 보스 사망 상태 구현

- Content/SciFi_Octopus/Mesh/Phy_SciFi_Octopus_PhysicsAsset.uasset
- Content/_AbyssDiver/Blueprints/Boss/Kraken/BP_Kraken.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/KDY.umap
- Source/AbyssDiverUnderWorld/Boss/Boss.cpp
- Source/AbyssDiverUnderWorld/Boss/BossAIController.cpp
- Source/AbyssDiverUnderWorld/Boss/BossAIController.h
- Source/AbyssDiverUnderWorld/Boss/Task/BTTask_BossAttack.cpp
- Source/AbyssDiverUnderWorld/Boss/Task/BTTask_BossChasing.cpp
- Source/AbyssDiverUnderWorld/Boss/Task/BTTask_BossIdle.cpp
- Source/AbyssDiverUnderWorld/Boss/Task/BTTask_BossInvestigate.cpp
- Source/AbyssDiverUnderWorld/Boss/Task/BTTask_BossMove.cpp
- Source/AbyssDiverUnderWorld/Boss/Task/BTTask_Detected.cpp
---
- TakeDamage 호출 시 부위 정보 출력 -> 캐릭터의 공격 로직 구현되면 완성할 예정
- Task의 캐스팅 최소화
---
---
---
> [Update] 보스 부위 타격 틀 구현

- Content/MineableRocks/MineableRocksProject/Player/BP_PlayerController.uasset
- Content/_AbyssDiver/Blueprints/UI/InventoryUI/WBP_AllInventoryWidget.uasset
- Content/_AbyssDiver/Blueprints/UI/InventoryUI/WBP_DragPreview.uasset
- Content/_AbyssDiver/Blueprints/UI/InventoryUI/WBP_InventorySlotWidget.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/HGYTest/BP_DDInventorySlot.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/HGYTest/HGY.umap
- Content/_AbyssDiver/Maps/Prototypes_Test/HGYTest/WBP_InputTest.uasset
- Source/AbyssDiverUnderWorld/Interactable/Item/ADItemBase.cpp
- Source/AbyssDiverUnderWorld/Inventory/ADInventoryComponent.cpp
- Source/AbyssDiverUnderWorld/Inventory/ADInventoryComponent.h
- Source/AbyssDiverUnderWorld/UI/AllInventoryWidget.cpp
- Source/AbyssDiverUnderWorld/UI/AllInventoryWidget.h
- Source/AbyssDiverUnderWorld/UI/DragPreviewWidget.cpp
- Source/AbyssDiverUnderWorld/UI/DragPreviewWidget.h
- Source/AbyssDiverUnderWorld/UI/InventoryDDO.cpp
- Source/AbyssDiverUnderWorld/UI/InventoryDDO.h
- Source/AbyssDiverUnderWorld/UI/InventorySlotWidget.cpp
- Source/AbyssDiverUnderWorld/UI/InventorySlotWidget.h
- Source/AbyssDiverUnderWorld/UI/InventoryWidget.cpp
- Source/AbyssDiverUnderWorld/UI/InventoryWidget.h
---
🎉 add
-DragDropOperation 클래스 추가
-드래그 시 나타날 PriviewWidget 추가
✨ update
-드래그 앤 드랍 구현(실제 기능은X 디버그 메시지 출력만)
-무게와 가격 UI 표시 추가
[저번 PR 피드백 반영]
-Refresh 오타 수정
-AllInventoryWidget 생성 부분 멀티플레이 고려 한번만 생성되도록 수정
♻️ refactor
-아이템 추가 후 인벤토리 정보 부분 OnInventoryInfoUpdate로 리팩토링
---
---
---
> 드래그 드랍 기능 구현(디버그 메시지 출력만), 무게/가치 UI표시 구현

- Content/_AbyssDiver/Blueprints/UI/ShopUI/M_ItemMesh.uasset
- Content/_AbyssDiver/Blueprints/UI/ShopUI/RT_ItemMesh.uasset
- Content/_AbyssDiver/Blueprints/UI/ShopUI/WBP_ElementInfoPanel.uasset
- Content/_AbyssDiver/Blueprints/UI/ShopUI/WBP_Shop.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/HSRTest/BP_TestShop.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/HSRTest/DT_ItemMestTableTest.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/HSRTest/HSR_Test.umap
- Source/AbyssDiverUnderWorld/AbyssDiverUnderWorld.h
- Source/AbyssDiverUnderWorld/Shops/Shop.cpp
- Source/AbyssDiverUnderWorld/Shops/Shop.h
- Source/AbyssDiverUnderWorld/Shops/ShopItemEntryData.cpp
- Source/AbyssDiverUnderWorld/Shops/ShopItemEntryData.h
- Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopElementInfoWidget.cpp
- Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopElementInfoWidget.h
- Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopItemSlotWidget.cpp
- Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopItemSlotWidget.h
- Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopWidget.cpp
- Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopWidget.h
---
- 상점 아이템 클릭할 때마다 그에 맞는 메쉬와 아이템 정보 표시 기능
- 다만 메쉬는 클라이언트 한 쪽에서만 UI에 반영됨 -> 에디터 버그로 추정, 실제 멀티플레이 테스트 필요
- AbyssDiverUnderWorld : LOGV, LOGVN 로그 호출 라인 표시 추가
> ✨ update 상점 아이템 클릭시 메쉬 출현, 정보 표시 기능 구현 및 기타

- Source/AbyssDiverUnderWorld/Container/FStructContainer.h
- Source/AbyssDiverUnderWorld/DataRow/FADItemDataRow.h
- Source/AbyssDiverUnderWorld/Interactable/Item/ADItemBase.cpp
- Source/AbyssDiverUnderWorld/Inventory/ADInventoryComponent.cpp
- Source/AbyssDiverUnderWorld/Inventory/ADInventoryComponent.h
- Source/AbyssDiverUnderWorld/UI/AllInventoryWidget.cpp
- Source/AbyssDiverUnderWorld/UI/InventorySlotWidget.cpp
- Source/AbyssDiverUnderWorld/UI/InventoryWidget.cpp
- Source/AbyssDiverUnderWorld/UI/InventoryWidget.h
---
✨ update
-InventoryComponent
remove와 transfer 기능 구현 및 add 수정(배열에 추가하는 것에서 미리 추가하고 Quantity만 조정하는 것으로 변경)
접두어 변경 Server_->S_
-ADItemBase
폰에서 인벤토리 컴포넌트 가져오는 것에서 플레이어 컨트롤러로 변경
-FADItemDataRow
StaticMesh 변수 추가
🐛 bugfix
-InventorySlotWidget
Brush 오류 -> GetBrush() 사용
-채광 시 위젯에서 나는 오류
RefreshInventoryInfo가 AllInventoryWidget이 Collapse 되었을 때 실행되어서 발생한 오류여서 델리게이트 바인딩으로 해결
---
---
---
> Auto stash before rebase of "HGY" onto "dev"

- Source/AbyssDiverUnderWorld/Character/OxygenComponent.cpp
- Source/AbyssDiverUnderWorld/Character/OxygenComponent.h
- Source/AbyssDiverUnderWorld/Character/UnderwaterCharacter.cpp
- Source/AbyssDiverUnderWorld/Character/UnderwaterCharacter.h
---
- 현재 산소, 최대 산소, 산소 소모율을 가지고 있는 산소 컴포넌트를 작성했습니다.
- 현재는 Tick 기반으로 작성되었지만 추후에 Timer 기반으로 Refactoring 하겠습니다.
- 캐릭터에 Oxygen Component 추가
---
---
---
> Oxygen Component 추가

- Content/SwimComponent/Blueprints/BuoyancyHelper/BP_BuoyancyHelper.uasset
- Content/_AbyssDiver/Blueprints/UI/ShopUI/WBP_ElementInfoPanel.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/HSRTest/BPC_ShopInteraction.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/HSRTest/BP_HSRTestUnderWaterCharacter.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/HSRTest/BP_TestGameMode.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/HSRTest/HSR_Test.umap
- Source/AbyssDiverUnderWorld/Shops/Shop.cpp
- Source/AbyssDiverUnderWorld/Shops/Shop.h
- Source/AbyssDiverUnderWorld/Shops/ShopInteractionComponent.cpp
- Source/AbyssDiverUnderWorld/Shops/ShopInteractionComponent.h
- Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopElementInfoWidget.cpp
- Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopElementInfoWidget.h
---
- 예상 flow
- 캐릭터에서 Interaction을 호출(서버) -> Shop의 Interact를 호출(서버) -> ShopInteractionComponent의 C_OpenShop 호출(클라)
- 이후 Shop의 OpenShop 호출(클라)하여 UI 열기
- BuyItem 밑작업
- BP_BuoyancyHelper 컴파일 오류로 인해 임시로 로직 비활성화
---
BP_BuoyancyHelper 컴파일 오류로 인해 임시로 로직 비활성화
---
> 상점과 상호작용해서 상점 UI 열기 및 기타

- Source/AbyssDiverUnderWorld/Interactable/Item/ADItemBase.cpp
- Source/AbyssDiverUnderWorld/Interactable/Item/ADItemBase.h
- Source/AbyssDiverUnderWorld/Interactable/Item/ADOreRock.cpp
- Source/AbyssDiverUnderWorld/Interactable/Item/ADOreRock.h
- Source/AbyssDiverUnderWorld/Interface/IADInteractable.h
- Source/AbyssDiverUnderWorld/Shops/Shop.cpp
- Source/AbyssDiverUnderWorld/Shops/Shop.h
- Source/AbyssDiverUnderWorld/Shops/ShopInteractionComponent.cpp
---
- GetInteractableComponent 함수 구현 강제 
- ShopInteractionComponent Replicate 활성화
- 상점 구매 로직 작성중
> ✨ update IADInteractable -> GetInteractableComponent 함수 구현 강제 및 기타

- Content/_AbyssDiver/Blueprints/UI/ShopUI/WBP_ElementInfoPanel.uasset
- Content/_AbyssDiver/Blueprints/UI/ShopUI/WBP_ShopItemSlot.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/HSRTest/BP_TestShop.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/HSRTest/HSR_Test.umap
- Source/AbyssDiverUnderWorld/Shops/Shop.cpp
- Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopElementInfoWidget.cpp
- Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopElementInfoWidget.h
- Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopItemSlotWidget.cpp
- Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopItemSlotWidget.h
---
- 현재는 로그만 출력, 소유 자금 차감 및 인벤토리에 아이템 추가 로직 필요
- 마우스 커서 올리면 툴팁 띄워줌.
---
> ✨ update 구매 로직 임시 작업 완료, 툴팁 띄우기 완료

- Content/_AbyssDiver/Blueprints/Character/BP_UnderwaterCharacter.uasset
- Source/AbyssDiverUnderWorld/Character/UnderwaterCharacter.cpp
- Source/AbyssDiverUnderWorld/Character/UnderwaterCharacter.h
- Source/AbyssDiverUnderWorld/Character/UnitBase.cpp
---
- 상호 작용 컴포넌트 연동
- Interaction Component 추가
- Interaction Getter 추가
- 레이더 컴포넌트 연동
- UnitBase에 Radar Tag 추가
- BP_UnderwaterCharacter에 Radar Return BP 추가
---
---
---
> Add: Interaction, Radar Component 연동

- Content/_AbyssDiver/DataTable/DT_UpgradeData.uasset
- Source/AbyssDiverUnderWorld/DataRow/ADUpgradeDataRow.cpp
- Source/AbyssDiverUnderWorld/DataRow/ADUpgradeDataRow.h
- Source/AbyssDiverUnderWorld/Subsystems/ADTestGameInstance.cpp
- Source/AbyssDiverUnderWorld/Subsystems/ADTestGameInstance.h
- Source/AbyssDiverUnderWorld/Subsystems/DataTableSubsystem.cpp
- Source/AbyssDiverUnderWorld/Subsystems/DataTableSubsystem.h
---
DataTableSubsystem에 데이터 테이블 통합
> DataTableSubsystem에 데이터 테이블 통합

- Content/_AbyssDiver/DataTable/DT_DropEntry.uasset
- Source/AbyssDiverUnderWorld/Interactable/Item/ADExchangeableItem.cpp
- Source/AbyssDiverUnderWorld/Interactable/Item/ADOreRock.cpp
- Source/AbyssDiverUnderWorld/Interactable/Item/ADOreRock.h
- Source/AbyssDiverUnderWorld/Interactable/Item/Component/ADInteractionComponent.cpp
- Source/AbyssDiverUnderWorld/Interactable/OtherActors/ADDrone.cpp
- Source/AbyssDiverUnderWorld/Interactable/OtherActors/ADDrone.h
- Source/AbyssDiverUnderWorld/Interactable/OtherActors/ADDroneSeller.cpp
- Source/AbyssDiverUnderWorld/Interactable/OtherActors/ADDroneSeller.h
- Source/AbyssDiverUnderWorld/Interface/IADInteractable.h
---
채광/채집/제출 기능을 클라이언트에서도 할 수 있고 그에 대한 결과가 네트워크 상에서 반영되도록 구현했습니다.
ADExchangeableItem ADDroneSeller, ADDrone
> 리플리케이션을 이용해서 움직이는 모습이 클라이언트에도 반영되도록 만들었습니다.
ADOreRock
> FX 효과를 RepNotify로 만들어서 클라이언트에도 효과가 보이도록 만들었습니다.
ADInteractableComponent
> ServerRPC를 이용해서 모든 상호작용 가능한 오브젝트들이 클라이언트의 캐릭터와도 상호작용 가능하도록 만들었습니다.
ADDrone, ADDroneSeller
> 목표 금액을 채우지 않으면 Drone의 외곽선이 표시되지 않도록 만들었습니다.
---
---
---
> 채광/채집 네트워크 연결

- Content/MineableRocks/MineableRocksProject/Player/BP_PlayerController.uasset
- Content/MineableRocks/MineableRocksProject/Player/BP_ThirdPersonCharacter.uasset
- Content/_AbyssDiver/DataTable/DT_Items.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/HGYTest/BP_TestHGYGameMode.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/HGYTest/HGY.umap
- Content/_AbyssDiver/Maps/Prototypes_Test/HGYTest/TestActor.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/HGYTest/WBP_InputTest.uasset
- Source/AbyssDiverUnderWorld/Framework/ADPlayerController.cpp
- Source/AbyssDiverUnderWorld/Framework/ADPlayerState.cpp
- Source/AbyssDiverUnderWorld/Framework/ADPlayerState.h
- Source/AbyssDiverUnderWorld/Interactable/Item/ADItemBase.cpp
- Source/AbyssDiverUnderWorld/Inventory/ADInventoryComponent.cpp
- Source/AbyssDiverUnderWorld/Inventory/ADInventoryComponent.h
- Source/AbyssDiverUnderWorld/Subsystems/DataTableSubsystem.cpp
- Source/AbyssDiverUnderWorld/Subsystems/DataTableSubsystem.h
- Source/AbyssDiverUnderWorld/UI/InventorySlotWidget.cpp
---
- 드래그 앤 드랍 시 아이템 스폰되는 기능 추가
- AddInventoryItem Count로 -1 입력 시 전체 버리기로 수정
- ADPlayerState에 인벤토리 컴포넌트 추가
(추후 플레이어 컨트롤러나 플레이어 스테이트에 Tab - ToggleInventoryShowed 바인딩 필요)
---
---
---
> 드래그 앤 드랍 기능 구현, 인벤토리 컴포넌트 ADPlayerState에 부착

- Content/_AbyssDiver/Maps/Prototypes_Test/HSRTest/HSR_Test.umap
- Source/AbyssDiverUnderWorld/Framework/ADPlayerController.cpp
- Source/AbyssDiverUnderWorld/Framework/ADPlayerState.cpp
- Source/AbyssDiverUnderWorld/Framework/ADPlayerState.h
---
- PlayerController에서 초기화 -> PlayerState에서 초기화
---
> 인벤토리 초기화 시점 변경

- Content/_AbyssDiver/Blueprints/Character/BP_UnderwaterCharacter.uasset
- Content/_AbyssDiver/Input/IA_Plyaer/IA_Sprint.uasset
- Content/_AbyssDiver/Input/IMC_Player.uasset
- Source/AbyssDiverUnderWorld/Character/StaminaComponent.cpp
- Source/AbyssDiverUnderWorld/Character/StaminaComponent.h
- Source/AbyssDiverUnderWorld/Character/UnderwaterCharacter.cpp
- Source/AbyssDiverUnderWorld/Character/UnderwaterCharacter.h
- Source/AbyssDiverUnderWorld/Character/UpgradeComponent.cpp
- Source/AbyssDiverUnderWorld/Character/UpgradeComponent.h
---
- Sprint Component 추가
- 캐릭터 Sprint Component 연동
- Upgrade Component 네트워크 연동 추가
---
---
---
> Add: Sprint 기능 추가, Upgrade Component 네트워크 연동 추가

- Content/MineableRocks/Demo/Characters/Mannequins/Meshes/SKM_Quinn_Simple.uasset
- Content/MineableRocks/Demo/Characters/Mannequins/Meshes/SK_Mannequin.uasset
- Content/_AbyssDiver/Blueprints/Interactables/Item/Weapon/BP_ADFiringWeapon.uasset
- Content/_AbyssDiver/Blueprints/Projectile/BP_ADProjectileBase.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/HGYTest/InteractTest.umap
- Content/speargun/M_SpearGun.uasset
- Content/speargun/SKM_SpearGun.uasset
- Content/speargun/SK_SpearGun.uasset
- Content/speargun/SpearGun.uasset
- Content/speargun/SpearGun1.uasset
- Content/speargun/SpearGun_Arrow.uasset
- Source/AbyssDiverUnderWorld/Interactable/Item/Weapon/ADFiringWeapon.cpp
- Source/AbyssDiverUnderWorld/Interactable/Item/Weapon/ADFiringWeapon.h
- Source/AbyssDiverUnderWorld/Inventory/ADInventoryComponent.cpp
- Source/AbyssDiverUnderWorld/Projectile/ADProjectileBase.cpp
- Source/AbyssDiverUnderWorld/Projectile/ADProjectileBase.h
---
-ProjectileBase 생성
-FiringWeapon 생성(추후 삭제 예정)
-기타 테스트용 파일 생성
---
---
---
> ProjectileBase 및 SpearGun(추후 삭제 예정) 생성

- Content/_AbyssDiver/Blueprints/UI/ShopUI/WBP_Shop.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/HSRTest/HSR_Test.umap
- Source/AbyssDiverUnderWorld/Shops/Shop.cpp
- Source/AbyssDiverUnderWorld/Shops/Shop.h
- Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopWidget.cpp
- Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopWidget.h
---
- 클라이언트에서 상점 아이템 목록 초기화 제대로 되지 않는 현상 수정
- 클라이언트에서 아이템 구메 제대로 되지 않는 현상 수정
---
> 🐛 bugfix 상점 버그 수정 ✨ update 닫기 버튼 추가

- Content/MineableRocks/MineableRocksProject/Player/BP_ThirdPersonCharacter.uasset
- Content/_AbyssDiver/DataTable/DT_Items.uasset
- Source/AbyssDiverUnderWorld/AbyssDiverUnderWorld.Build.cs
- Source/AbyssDiverUnderWorld/DataRow/FADItemDataRow.h
- Source/AbyssDiverUnderWorld/Interactable/Item/ADUseItem.cpp
- Source/AbyssDiverUnderWorld/Interactable/Item/ADUseItem.h
- Source/AbyssDiverUnderWorld/Interactable/Item/UseFunction/RecoveryOxygen.cpp
- Source/AbyssDiverUnderWorld/Interactable/Item/UseFunction/RecoveryOxygen.h
- Source/AbyssDiverUnderWorld/Interactable/Item/UseFunction/ToggleEquipUseFunction.cpp
- Source/AbyssDiverUnderWorld/Interactable/Item/UseFunction/ToggleEquipUseFunction.h
- Source/AbyssDiverUnderWorld/Interface/IADUsable.cpp
- Source/AbyssDiverUnderWorld/Interface/IADUsable.h
- Source/AbyssDiverUnderWorld/Inventory/ADInventoryComponent.cpp
- Source/AbyssDiverUnderWorld/Inventory/ADInventoryComponent.h
- Source/AbyssDiverUnderWorld/Projectile/ADProjectileBase.cpp
- Source/AbyssDiverUnderWorld/Projectile/ADProjectileBase.h
- Source/AbyssDiverUnderWorld/UI/InventorySlotWidget.cpp
- 인벤토리 사용 기능 인터페이스 제작
- 인벤토리 컴포넌트에 사용 함수 생성
- ProjectileComponent collision hit -> beginoverlap
---
---
---
---
> ✨ update 인벤토리 아이템 사용 기능

- Content/_AbyssDiver/Maps/Prototypes_Test/KKS/BP_Capture.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/KKS/KKS_LocomotionTest.umap
- Source/AbyssDiverUnderWorld/Character/PlayerComponent/PlayerHUDComponent.h
- Source/AbyssDiverUnderWorld/Character/PlayerHUDWidget.h
- Source/AbyssDiverUnderWorld/Character/UnderwaterCharacter.cpp
- Source/AbyssDiverUnderWorld/Character/UnderwaterCharacter.h
---
- Captrue 상태 구현
- 현재 이동 입력, 회전 입력을 정지
- Collider 비활성화
---
https://github.com/user-attachments/assets/ed11d203-b22e-4454-85b7-eafbca917d25
---
---
> Add: Capture 기능 추가

- Content/MineableRocks/MineableRocksProject/Audio/SC_BoulderBreak.uasset
- Content/MineableRocks/MineableRocksProject/Player/BP_PlayerController.uasset
- Content/MineableRocks/MineableRocksProject/Player/BP_ThirdPersonCharacter.uasset
- Content/_AbyssDiver/Blueprints/Interactables/Item/BP_ADOreRock.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/CWSTest/CWS_TestGameMode.uasset
- Source/AbyssDiverUnderWorld/Interactable/Item/ADUseItem.cpp
- Source/AbyssDiverUnderWorld/Interactable/Item/Component/EquipUseComponent.cpp
- Source/AbyssDiverUnderWorld/Interactable/Item/Component/EquipUseComponent.h
- Source/AbyssDiverUnderWorld/Inventory/ADInventoryComponent.cpp
---
EquipComponent
> HarpoonFire 함수 변경 (연사 속도 적용 -> 재장전 또는 연사 딜레이 중 발사 X)
> HarpoonFire, ToggleBoost, ToggleNightVision 모두 네트워크 로직 적용 (클라이언트에서 작동 확인)
> Initialize 함수 : 장착/장착 해제 시 소모된 Amount가 저장되지 않는 문제를 해결
ADOreRock
> 채광 시 사운드에 어테뉴에이션 적용
---
---
---
> EquipComponent 내부 로직 개선 (Harpoon : 연사 속도, 재장전 로직 추가) 네트워크 적용

- Content/Shark1/Animations/AM_Shark_Attack1.uasset
- Content/Shark1/Animations/AM_Shark_Attack2.uasset
- Content/Shark1/Mesh/SKEL_Shark1.uasset
- Content/_AbyssDiver/Blueprints/ABP/Boss/AlienShark/ABP_AlienShark.uasset
- Content/_AbyssDiver/Blueprints/Boss/AlienShark/BB_AlienShark.uasset
- Content/_AbyssDiver/Blueprints/Boss/AlienShark/BP_AlienShark.uasset
- Content/_AbyssDiver/Blueprints/Boss/AlienShark/BP_AlienSharkAIController.uasset
- Content/_AbyssDiver/Blueprints/Boss/AlienShark/BT_AlienShark.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/KDYTest/KDY.umap
- Source/AbyssDiverUnderWorld/Boss/AlienShark/AlienShark.cpp
- Source/AbyssDiverUnderWorld/Boss/AlienShark/AlienShark.h
- Source/AbyssDiverUnderWorld/Boss/Task/AlienShark/BTTask_AlienSharkIdle.cpp
- Source/AbyssDiverUnderWorld/Boss/Task/AlienShark/BTTask_AlienSharkIdle.h
- Source/AbyssDiverUnderWorld/Boss/Task/AlienShark/BTTask_AlienSharkMove.cpp
- Source/AbyssDiverUnderWorld/Boss/Task/AlienShark/BTTask_AlienSharkMove.h
---
- 이동, 공격, 감지 등의 기본 로직 구현
---
---
---
> [Add, Update] AlienShark 클래스 기초 구현

- Content/_AbyssDiver/Blueprints/Gimmic/SpawnPoint/BP_SpawnPoint.uasset
- Content/_AbyssDiver/Blueprints/Gimmic/Spawner/BP_OreSpawner.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/KDYTest/KDY.umap
- Source/AbyssDiverUnderWorld/Boss/Task/Boss/BTTask_Detected.cpp
- Source/AbyssDiverUnderWorld/Gimmic/SpawnPoint/SpawnPoint.cpp
- Source/AbyssDiverUnderWorld/Gimmic/SpawnPoint/SpawnPoint.h
- Source/AbyssDiverUnderWorld/Gimmic/Spawner/Ore/OreSpawner.cpp
- Source/AbyssDiverUnderWorld/Gimmic/Spawner/Ore/OreSpawner.h
- Source/AbyssDiverUnderWorld/Gimmic/Spawner/Spawner.cpp
- Source/AbyssDiverUnderWorld/Gimmic/Spawner/Spawner.h
---
- 일단은 페이즈별 스폰이 아닌 맵 전체를 대상으로 Spawn
- 1. BP_OreSpawner 를 맵에 배치
- 2. 원하는 광석 스폰 지점에 BP_SpawnPoint를 배치
---
- 최소 광석 수 1개, 최대 광석 수 2개로 지정해놓은 결과
---
---
> [Add, Update] 광석 스포너 구현

- Content/_AbyssDiver/Blueprints/Gimmic/SpawnPoint/BP_MonsterSpawnPoint.uasset
- Content/_AbyssDiver/Blueprints/Gimmic/SpawnPoint/BP_OreSpawnPoint.uasset
- Content/_AbyssDiver/Blueprints/Gimmic/SpawnPoint/BP_SpawnPoint.uasset
- Content/_AbyssDiver/Blueprints/Gimmic/Spawner/BP_MonsterSpawner.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/KDYTest/KDY.umap
- Source/AbyssDiverUnderWorld/Gimmic/SpawnPoint/Monster/MonsterSpawnPoint.cpp
- Source/AbyssDiverUnderWorld/Gimmic/SpawnPoint/Monster/MonsterSpawnPoint.h
- Source/AbyssDiverUnderWorld/Gimmic/SpawnPoint/Ore/OreSpawnPoint.cpp
- Source/AbyssDiverUnderWorld/Gimmic/SpawnPoint/Ore/OreSpawnPoint.h
- Source/AbyssDiverUnderWorld/Gimmic/Spawner/Monster/MonsterSpawner.cpp
- Source/AbyssDiverUnderWorld/Gimmic/Spawner/Monster/MonsterSpawner.h
- Source/AbyssDiverUnderWorld/Gimmic/Spawner/Ore/OreSpawner.cpp
- Source/AbyssDiverUnderWorld/Gimmic/Spawner/Spawner.cpp
- Source/AbyssDiverUnderWorld/Gimmic/Spawner/Spawner.h
---
- 몬스터를 스폰하는 스포너 클래스 구현
- /Game/_AbyssDiver/Blueprints/Gimmic/Spawner/BP_MonsterSpawner 를 맵에 배치
- /Game/_AbyssDiver/Blueprints/Gimmic/SpawnPoint/BP_MonsterSpawnPoint를 원하는 스폰 지점마다 배치
- 속성
- MonsterClass : 스폰 되기를 바라는 몬스터 클래스와 최대 개체 수를 지정할 수 있음
- MinMonsterSpawnCount : 최소 몬스터 스폰 개체 수
- MaxMonsterSpawnCount : 최대 몬스터 스폰 개체 수
---
---
---
> [Add, Update] Monster Spawner 구현

- Content/_AbyssDiver/Blueprints/UI/UI/WB_Compass.uasset
> 🐛 bugfix 나침반 버그 수정

- Content/_AbyssDiver/Blueprints/Interactables/Item/BP_ADOreRock.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/CWSTest/CWS.umap
- Source/AbyssDiverUnderWorld/Interactable/Item/ADOreRock.cpp
- Source/AbyssDiverUnderWorld/Interactable/Item/Component/ADInteractionComponent.cpp
---
ADInteractionComponent
> FindComponent -> Getter로 최적화
> HoldMode가 아닌 오브젝트에도 UI가 띄워지는 문제 해결
---
---
---
> update  [ADInteractionComponent] 최적화, UI가 잘못 띄워지는 문제 수정

- Config/DefaultEngine.ini
- Source/AbyssDiverUnderWorld/Interactable/Item/Component/EquipUseComponent.cpp
- Source/AbyssDiverUnderWorld/Projectile/ADProjectileBase.cpp
---
발사체 발사 시에 crash 나던 것 수정
Default.ini, ADProjectileBase
> null check 추가
> Monster 콜리전과 Monster Preset 추가
---
---
---
> [update] 발사체 발사 시에 crash 나던 것 수정

- Content/_AbyssDiver/Blueprints/Framework/BP_ADGameInstance.uasset
- Content/_AbyssDiver/DataTable/DT_Items.uasset
- Content/_AbyssDiver/DataTable/DT_Projectile.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/HGYTest/BP_TestFire.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/HGYTest/InteractTest.umap
- Source/AbyssDiverUnderWorld/DataRow/FADItemDataRow.h
- Source/AbyssDiverUnderWorld/Framework/ADGameInstance.h
- Source/AbyssDiverUnderWorld/Projectile/ADSpearGunBullet.cpp
- Source/AbyssDiverUnderWorld/Projectile/ADSpearGunBullet.h
---
- DT_Projectile 생성 및 지정
- SpearGunBullet Type 지정 함수 위치 수정
---
---
---
> SpearGunBullet 관련 함수 위치 변경 및 DT_Projectile 지정

- Content/_AbyssDiver/Blueprints/Character/BP_UnderwaterCharacter.uasset
- Content/_AbyssDiver/DataTable/DT_Items.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/HGYTest/WBP_InputTest.uasset
- Source/AbyssDiverUnderWorld/Container/FStructContainer.h
- Source/AbyssDiverUnderWorld/Interactable/Item/ADUseItem.cpp
- Source/AbyssDiverUnderWorld/Interactable/Item/ADUseItem.h
- Source/AbyssDiverUnderWorld/Interactable/Item/Component/EquipUseComponent.cpp
- Source/AbyssDiverUnderWorld/Interactable/Item/Component/EquipUseComponent.h
- Source/AbyssDiverUnderWorld/Inventory/ADInventoryComponent.cpp
- Source/AbyssDiverUnderWorld/Inventory/ADInventoryComponent.h
---
EquipUseComponent에서 TMap을 이용해서 Amount 값을 초기화 하던 방식
> ADInventoryComponent와 연동해서 Item에 있는 FItemData를 받아오는 방식으로 수정
> Spawn하는 클래스 변경 (ProjectileBase->SpearGunBullet)
---
---
---
> EquipComponent에서 변동값 초기화 방식을 개선 (RowName을 이용한 TMap 방식 -> 아이템 인스턴스에서 FItemData를 받아오는 방식)

- Content/_AbyssDiver/Maps/Prototypes_Test/HGYTest/HGY.umap
- Content/_AbyssDiver/Maps/Prototypes_Test/HGYTest/T_Moon.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/HGYTest/T_NVGVinetting.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/HGYTest/WBP_NightVisionGoggle.uasset
- Source/AbyssDiverUnderWorld/Interactable/Item/ADUseItem.h
- Source/AbyssDiverUnderWorld/Inventory/ADInventoryComponent.cpp
- Source/AbyssDiverUnderWorld/Inventory/ADInventoryComponent.h
- Source/AbyssDiverUnderWorld/UI/ADNightVisionGoggle.cpp
- Source/AbyssDiverUnderWorld/UI/ADNightVisionGoggle.h
- Source/AbyssDiverUnderWorld/UI/InventorySlotWidget.cpp
- Source/AbyssDiverUnderWorld/UI/InventorySlotWidget.h
- Source/AbyssDiverUnderWorld/UI/InventoryWidget.cpp
---
- NightVisionUI 완성
- 드래그 앤 드랍으로 슬롯 교체 수정
- 드롭 아이템 물 저항 계수 값 증가
---
---
---
> NightVisionUI 및 기타 버그 수정

- Content/_AbyssDiver/Blueprints/UI/UI/WB_Compass.uasset
---
-나침반 오류 생긴다고 제보 받아서 수정해서 올립니다!!
---
---
---
> ✨ update: 나침반 수정

- Source/AbyssDiverUnderWorld/Shops/Shop.cpp
- Source/AbyssDiverUnderWorld/Shops/Shop.h
- Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopElementInfoWidget.cpp
- Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopElementInfoWidget.h
---
- 클라이언트에서 상점이 제대로 초기화되지 않는 버그 해결(에디터와 패키징 간의 Enum 개수 불일치, Beginplay 호출 시점 불명확)
- Shop의 로그는 LOGS로 모두 변경
---
> 🐛 bugfix 패키징 클라이언트 상점 버그 해결 및 기타

- Content/_AbyssDiver/DataTable/DT_Items.uasset
- Source/AbyssDiverUnderWorld/DataRow/FADItemDataRow.h
---
- Quantity, Mesh는 이제 사용하지 않으므로 삭제
- 테스트용으로 띄울 Description에 내용 추가
---
> ✨ update 아이템 데이터 테이블 필요 없는 Column 삭제, Description 임시로 추가

- Content/_AbyssDiver/Blueprints/Framework/BP_ADGameInstance.uasset
- Content/_AbyssDiver/DataTable/DT_ShopItemMeshTransform.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/HSRTest/BP_TestShop.uasset
- Source/AbyssDiverUnderWorld/DataRow/ShopItemMeshTransformRow.cpp
- Source/AbyssDiverUnderWorld/DataRow/ShopItemMeshTransformRow.h
- Source/AbyssDiverUnderWorld/Framework/ADGameInstance.h
- Source/AbyssDiverUnderWorld/Shops/Shop.cpp
- Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopElementInfoWidget.cpp
- Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopElementInfoWidget.h
- Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopItemMeshPanel.cpp
- Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopItemMeshPanel.h
- Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopWidget.cpp
- Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopWidget.h
- Source/AbyssDiverUnderWorld/Subsystems/DataTableSubsystem.cpp
- Source/AbyssDiverUnderWorld/Subsystems/DataTableSubsystem.h
---
- 상점 미리보기 아이템 메쉬 초기 트랜스폼 설정용 자세한건 문서 참고
https://teamsparta.notion.site/1f92dc3ef5148034997efb190e850c95
---
> 🎉 add ✨ update 상점 아이템 메쉬 트랜스폼 설정 데이터 테이블 도입

- Content/_AbyssDiver/Blueprints/UI/InventoryUI/WBP_AllInventoryWidget.uasset
- Content/_AbyssDiver/Blueprints/UI/InventoryUI/WBP_ToggleWidget.uasset
- Content/_AbyssDiver/DataTable/DT_Items.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/HGYTest/HGY.umap
- Source/AbyssDiverUnderWorld/Interactable/Item/UseFunction/EnableShield.cpp
- Source/AbyssDiverUnderWorld/Interactable/Item/UseFunction/EnableShield.h
- Source/AbyssDiverUnderWorld/Interactable/Item/UseFunction/RecoveryOxygen.cpp
- Source/AbyssDiverUnderWorld/Inventory/ADInventoryComponent.cpp
- Source/AbyssDiverUnderWorld/Inventory/ADInventoryComponent.h
- Source/AbyssDiverUnderWorld/UI/MissionSelectWidget.cpp
- Source/AbyssDiverUnderWorld/UI/ToggleWidget.cpp
- Source/AbyssDiverUnderWorld/UI/ToggleWidget.h
---
- AllInventoryWidget 이름 수정
- 슬롯 교체 크래시 해결
- 산소 기능 구현
---
---
---
> 피드백 반영 및 산소 기능 구현

- Source/AbyssDiverUnderWorld/Inventory/ADInventoryComponent.cpp
- Source/AbyssDiverUnderWorld/UI/InventoryWidget.cpp
---
- LocalPlayerControllers 에러 수정
---
---
---
> LocalPlayerControllers 에러 수정

- Source/AbyssDiverUnderWorld/Character/UpgradeComponent.cpp
- Source/AbyssDiverUnderWorld/Character/UpgradeComponent.h
---
이제 상점에서 업그레이드하면 돈 깎입니다
---
> ✨ update 상점에서 업그레이드시 돈 차감

- Content/_AbyssDiver/Blueprints/Framework/BP_ADPlayerController.uasset
- Content/_AbyssDiver/Blueprints/UI/UI/Fill.uasset
- Source/AbyssDiverUnderWorld/Character/PlayerComponent/PlayerHUDComponent.cpp
- Source/AbyssDiverUnderWorld/Character/PlayerComponent/PlayerHUDComponent.h
- Source/AbyssDiverUnderWorld/UI/PlayerStatusWidget.cpp
---
- PlayerHUDComponent랑 연동한게 잘 적용이 안돼서 다시 시도 했는데 연동이 잘 되었슴니다!
- 다음은 스테미나 나 체력 연동 해보도록 하겠습니당
---
---
- 어딘가에 또또 이상하게 구현한 부분이 있을 수 있슴니다...
- 
---
> ✨ update: 산소통 UI 연결

- Content/_AbyssDiver/Blueprints/Environmental_Factors/BP_EventTrigger.uasset
- Content/_AbyssDiver/Blueprints/Environmental_Factors/BP_Whale.uasset
- Source/AbyssDiverUnderWorld/Interactable/OtherActors/EventTriggers/EventTrigger.cpp
- Source/AbyssDiverUnderWorld/Interactable/OtherActors/EventTriggers/EventTrigger.h
- Source/AbyssDiverUnderWorld/Interface/Triggerable.cpp
- Source/AbyssDiverUnderWorld/Interface/Triggerable.h
- Source/AbyssDiverUnderWorld/Shops/Shop.cpp
- Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopWidget.cpp
---
- 오버렙 이벤트가 발동하면 등록된 액터들의 이벤트를 발동시킴 
- 오버랩 이벤트가 발동하면 행동할 객제를 표현하기 위한 인터페이스
- EventTrigger의 오버랩이 발동하면 TriggerEvent 함수가 발동
- 고래 순찰 로직 변경
- Shop : 필요 없는 주석 삭제
- ShopWiget : Super::NativeDestruct() 위치 변경
문서 참고
https://teamsparta.notion.site/EventTrigger-1fd2dc3ef514806f80fbc37d13fbe4bf
---
Spline에서 진행된 위치 기록용 변수 초기화
Current Spline Position을 시간마다 일정수치 더해주면서 그것에 해당하는 Spline 위치(Transform)으로 이동
Loop 모드일 경우 최대 Spline 위치에 도착했을 때 Current Spline Position을 0으로 초기화
오버렙 이벤트가 발동하면 틱 발동하도록
---
> 🎉 add EventTrigger, Triggerable 🩹 fix BP_Whale 및 기타

- Content/_AbyssDiver/Blueprints/UI/EquipUI/WBP_ChargeBattery.uasset
- Content/_AbyssDiver/Input/IA_Plyaer/IA_Inventory.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/HGYTest/HGY.umap
- Source/AbyssDiverUnderWorld/Container/FStructContainer.h
- Source/AbyssDiverUnderWorld/Framework/ADPlayerController.cpp
- Source/AbyssDiverUnderWorld/Framework/ADPlayerController.h
- Source/AbyssDiverUnderWorld/Interactable/Item/Component/EquipUseComponent.cpp
- Source/AbyssDiverUnderWorld/Interactable/Item/Component/EquipUseComponent.h
- Source/AbyssDiverUnderWorld/Inventory/ADInventoryComponent.cpp
- Source/AbyssDiverUnderWorld/Inventory/ADInventoryComponent.h
- Source/AbyssDiverUnderWorld/UI/ChargeBatteryWidget.cpp
- Source/AbyssDiverUnderWorld/UI/ChargeBatteryWidget.h
---
- 인벤토리 토글 방식 변경(Tab 누르면 인벤토리 보이고 떼면 사라짐)
- 배터리 충전 기능 구현
- 
---
---
---
> 배터리 충전 기능 추가

- Content/Shark1/Animations/Anim_Shark1_ForwardSwimExtraFast.uasset
- Content/Shark1/Animations/Anim_Shark1_ForwardSwimFast.uasset
- Content/_AbyssDiver/Blueprints/ABP/Boss/AlienShark/ABP_AlienShark.uasset
- Content/_AbyssDiver/Blueprints/ABP/Boss/AlienShark/BS_AlienShark.uasset
- Content/_AbyssDiver/Blueprints/Boss/AlienShark/BP_AlienShark.uasset
- Content/_AbyssDiver/Blueprints/Boss/AlienShark/BT_Enhanced_AlienShark.uasset
- Content/_AbyssDiver/Blueprints/Boss/AlienShark/EQS_FindHidePoint.uasset
- Content/_AbyssDiver/Blueprints/Gimmic/SafeZone/BP_SafeZone.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/KDYTest/KDY_Blood_Effect.umap
- Source/AbyssDiverUnderWorld/Boss/AlienShark/AlienShark.cpp
- Source/AbyssDiverUnderWorld/Boss/Boss.cpp
- Source/AbyssDiverUnderWorld/Boss/Boss.h
- Source/AbyssDiverUnderWorld/Boss/Task/Enhanced/BTTask_BloodDetected.cpp
- Source/AbyssDiverUnderWorld/Boss/Task/Enhanced/BTTask_Damaged.cpp
- Source/AbyssDiverUnderWorld/Boss/Task/Enhanced/BTTask_EnhancedIdle.cpp
- Source/AbyssDiverUnderWorld/Boss/Task/Enhanced/BTTask_HiddenPlayerChase.cpp
- Source/AbyssDiverUnderWorld/Boss/Task/Enhanced/BTTask_MoveToLocation.cpp
- Source/AbyssDiverUnderWorld/Boss/Task/Enhanced/BTTask_MoveToLocation.h
- Source/AbyssDiverUnderWorld/Boss/Task/Enhanced/BTTask_PlayerChase.cpp
- Source/AbyssDiverUnderWorld/Boss/Task/Enhanced/BTTask_PlayerChase.h
- Source/AbyssDiverUnderWorld/Boss/Task/Enhanced/BTTask_PlayerDetected.cpp
- Source/AbyssDiverUnderWorld/Gimmic/SafeZone/SafeZoneTriggerBox.cpp
- Source/AbyssDiverUnderWorld/Gimmic/SafeZone/SafeZoneTriggerBox.h
---
- Alien Shark의 이동속도에 따라 블렌딩한 애니메이션 출력
- MoveTo 함수로 회전만 시킨 후 실제 이동은 전방벡터로 수행
---
---
---
> [Update] 전방벡터 이동 및 Blend Space 연동

- Content/_AbyssDiver/Blueprints/Framework/BP_ADGameInstance.uasset
- Content/_AbyssDiver/DataTable/SoundData/DT_AmbientSFX.uasset
- Source/AbyssDiverUnderWorld/DataRow/SoundDataRow/AmbientDataRow.h
- Source/AbyssDiverUnderWorld/Framework/ADGameInstance.cpp
- Source/AbyssDiverUnderWorld/Framework/ADGameInstance.h
- Source/AbyssDiverUnderWorld/Subsystems/SoundSubsystem.cpp
- Source/AbyssDiverUnderWorld/Subsystems/SoundSubsystem.h
---
- AmbientSFX : 환경 소리용,  필요할 것 같아서 추가
- 리펙토링 : 일부 코드에 const 좀 붙임, 구조 살짝 변경
---
> ♻️ refactor ✨ update SoundSubsystem : AmbientSFX 타입 추가 및 리펙토링

- Content/_AbyssDiver/Maps/Prototypes_Test/KY/Shallow.umap
---
- NavMeshBound 수정
---
---
---
> [Update] 테스트 맵 수정

- Content/_AbyssDiver/DataTable/DT_Projectile.uasset
- Source/AbyssDiverUnderWorld/Container/FStructContainer.h
- Source/AbyssDiverUnderWorld/DataRow/FADProjectileDataRow.h
- Source/AbyssDiverUnderWorld/Interactable/Item/ADItemBase.h
- Source/AbyssDiverUnderWorld/Interactable/Item/ADUseItem.cpp
- Source/AbyssDiverUnderWorld/Interactable/Item/ADUseItem.h
- Source/AbyssDiverUnderWorld/Inventory/ADInventoryComponent.cpp
- Source/AbyssDiverUnderWorld/Inventory/ADInventoryComponent.h
- Source/AbyssDiverUnderWorld/Projectile/ADProjectileBase.cpp
- Source/AbyssDiverUnderWorld/Projectile/ADProjectileBase.h
- Source/AbyssDiverUnderWorld/Projectile/ADSpearGunBullet.cpp
- Source/AbyssDiverUnderWorld/Projectile/ADSpearGunBullet.h
- Source/AbyssDiverUnderWorld/UI/ChargeBatteryWidget.cpp
- Source/AbyssDiverUnderWorld/UI/ChargeBatteryWidget.h
---
- Hit 시 적에 화살 부착
- 폭탄 화살 burst 이펙트 추가
---
---
---
> Hit 시 화살 부착, 폭탄 화살 burst 이펙트 추가

- Source/AbyssDiverUnderWorld/Inventory/ADInventoryComponent.cpp
- Source/AbyssDiverUnderWorld/Inventory/ADInventoryComponent.h
---
- 인벤토리 copy 기능
---
---
---
> ✨ update 인벤토리 Copy 기능

- Content/DeepWaterStation/Meshes/SM_ChairA04.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/KY/Lobby_Test.umap
- Content/z3D_Radar/Meshes/3_Planes_SM.uasset
- Content/z3D_Radar/Meshes/Plane_SM.uasset
- Source/AbyssDiverUnderWorld/Framework/ADInGameState.cpp
- Source/AbyssDiverUnderWorld/Framework/ADInGameState.h
- Source/AbyssDiverUnderWorld/Framework/ADPlayerState.cpp
---
-  테스트 로비맵에 상점 추가
- 나나이트 적용 불가 SM에 나나이트 해제
- 맵 이동시 인벤토리 데이터 전달
---
> ✨ update 테스트 로비맵에 상점 추가, 나나이트 적용 불가 SM에 나나이트 해제, 맵 이동시 인벤토리 데이터 전달

- Content/_AbyssDiver/Blueprints/Boss/AlienShark/BP_AlienShark.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/KDYTest/KDY_Blood_Effect.umap
- Content/_AbyssDiver/Maps/Prototypes_Test/KDYTest/Shallow_KDY.umap
- Content/_AbyssDiver/Maps/Prototypes_Test/KY/Shallow.umap
- Source/AbyssDiverUnderWorld/Boss/BossAIController.cpp
- Source/AbyssDiverUnderWorld/Boss/Task/Enhanced/BTTask_MoveToLocation.cpp
- Source/AbyssDiverUnderWorld/Boss/Task/Enhanced/BTTask_MoveToLocation.h
---
- AI가 바닥 아래, 천장 위로 이동하려는 버그 현상 수정
- AI가 지형에 막히거나 NavMesh 밖으로 벗어났을 때 로그 출력 기능 구현
---
---
---
> [Update] AI NavMesh 조정

- Content/MineableRocks/MineableRocksProject/Audio/SC_Laser.uasset
- Source/AbyssDiverUnderWorld/Framework/ADPlayerController.cpp
- Source/AbyssDiverUnderWorld/Framework/ADPlayerController.h
- Source/AbyssDiverUnderWorld/Interactable/Item/Component/ADInteractionComponent.cpp
- Source/AbyssDiverUnderWorld/Interactable/Item/Component/ADInteractionComponent.h
- Source/AbyssDiverUnderWorld/Interactable/Item/Component/EquipUseComponent.cpp
- Source/AbyssDiverUnderWorld/Interactable/Item/Component/EquipUseComponent.h
- Source/AbyssDiverUnderWorld/Interactable/OtherActors/ADDrone.cpp
---
**ADPlayerController
레벨 넘어갈 때는 UI가 만들어지지 않는 버그**
> OnPossess 함수에 로직 이전
**ADInteractionCOmponent
채집하다가 다른 곳 보면 계속 이펙트가 나오는 버그**
> Hold 대상의 Componenet를 캐싱해서 새결
**EquipUseComponent
서버에는 총알 UI 업데이트가 안되던 버그**
> OnRep함수 서버 로직에 추가
---
---
---
> update 패키징 오류 개선

- Source/AbyssDiverUnderWorld/Container/FStructContainer.h
- Source/AbyssDiverUnderWorld/Interactable/Item/Component/EquipUseComponent.cpp
- Source/AbyssDiverUnderWorld/Inventory/ADInventoryComponent.cpp
- Source/AbyssDiverUnderWorld/Inventory/ADInventoryComponent.h
- Source/AbyssDiverUnderWorld/UI/ChargeBatteryWidget.cpp
---
- 충전 속도 조절
- 레벨 이동 시 배터리 충전 UI 활성화 안되는 버그 해결
- DPV 장착 안되어 있을 때 100% 이상 충전 시 % 줄어드는 버그 해결
- DPV 장착 했을 때 충전 시 101% 되는 버그 해결
---
---
---
> 배터리 충전 버그 해결

- Content/_AbyssDiver/Maps/Prototypes_Test/CWSTest/CWS.umap
- Content/_AbyssDiver/Maps/Prototypes_Test/CWSTest/Concrete_Pipe_vilidio_Raw.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/CWSTest/concrete_pipe_vilidio_raw1.uasset
- Content/_AbyssDiver/Materials/M_Chromatic.uasset
- Content/_AbyssDiver/Materials/M_GodRay.uasset
- Source/AbyssDiverUnderWorld/Character/UnderwaterCharacter.cpp
- Source/AbyssDiverUnderWorld/Character/UnderwaterCharacter.h
- Source/AbyssDiverUnderWorld/Framework/ADPlayerController.cpp
- Source/AbyssDiverUnderWorld/Framework/ADPlayerController.h
- Source/AbyssDiverUnderWorld/Interactable/Item/Component/EquipUseComponent.cpp
- Source/AbyssDiverUnderWorld/Interactable/Item/Component/EquipUseComponent.h
---
**M_GodRay, M_Chromatic**
>  God Rays, 색수차 효과 머터리얼 추가 
**( 사용 방법은 노션에 기재 )**
**DPV**
> Toggle 형식에서 Press, Release 형식으로 변환
**ADPlayerController**
> UI를 BeginPlay에서 SetPawn으로 이전 (레벨 변동에도 작동)
---
---
- DPV 로직을 변경하는 과정에서 불가피하게 UnderwaterCharacter 코드를 손 봤습니다. 경수님 시간 여유 되시면 확인 부탁드립니다.
---
> add, update : GodRays, Chromatic 머터리얼 추가, 오류 개선

- Content/_AbyssDiver/Blueprints/Framework/BP_ADGameInstance.uasset
- Content/_AbyssDiver/DataTable/MissionData/DT_AggroTriggerMissions.uasset
- Content/_AbyssDiver/DataTable/MissionData/DT_InteractionMissions.uasset
- Content/_AbyssDiver/DataTable/MissionData/DT_ItemCollectionMissions.uasset
- Content/_AbyssDiver/DataTable/MissionData/DT_ItemUseMissions.uasset
- Content/_AbyssDiver/DataTable/MissionData/DT_KillMonsterMissions.uasset
- Source/AbyssDiverUnderWorld/DataRow/MissionDataRow/AggroTriggerMissionRow.h
- Source/AbyssDiverUnderWorld/DataRow/MissionDataRow/InteractionMissionRow.h
- Source/AbyssDiverUnderWorld/DataRow/MissionDataRow/ItemCollectMissionRow.h
- Source/AbyssDiverUnderWorld/DataRow/MissionDataRow/ItemUseMissionRow.h
- Source/AbyssDiverUnderWorld/DataRow/MissionDataRow/KillMonsterMissionRow.h
- Source/AbyssDiverUnderWorld/DataRow/MissionDataRow/MissionBaseRow.h
- Source/AbyssDiverUnderWorld/Framework/ADGameInstance.h
- Source/AbyssDiverUnderWorld/Missions/AggroTriggerMission.cpp
- Source/AbyssDiverUnderWorld/Missions/AggroTriggerMission.h
- Source/AbyssDiverUnderWorld/Missions/InteractionMission.cpp
- Source/AbyssDiverUnderWorld/Missions/InteractionMission.h
- Source/AbyssDiverUnderWorld/Missions/ItemCollectionMission.cpp
- Source/AbyssDiverUnderWorld/Missions/ItemCollectionMission.h
- Source/AbyssDiverUnderWorld/Missions/ItemUseMission.cpp
- Source/AbyssDiverUnderWorld/Missions/ItemUseMission.h
- Source/AbyssDiverUnderWorld/Missions/KillMonsterMission.cpp
- Source/AbyssDiverUnderWorld/Missions/KillMonsterMission.h
- Source/AbyssDiverUnderWorld/Missions/MissionBase.cpp
- Source/AbyssDiverUnderWorld/Missions/MissionBase.h
- Source/AbyssDiverUnderWorld/Subsystems/MissionSubsystem.cpp
- Source/AbyssDiverUnderWorld/Subsystems/MissionSubsystem.h
- Source/AbyssDiverUnderWorld/UI/MissionData.h
- Source/AbyssDiverUnderWorld/UI/MissionSelectWidget.cpp
---
- 미션을 5종류로 나눠서 관리 : 어그로, 상호작용, 아이템 수집, 아이템 사용, 몬스터 사냥
- AggroTriggerMission, InteractionMission, ItemCollectionMission, ItemUseMission, KillMonsterMission
- 선택된 미션을 토대로 클래스를 만들어서 관리할 예정
- 더 복합적인 미션은 이 클래스들 중에서 유사한 것을 상속 받아 구현할 생각
- 미션 데이터 관리, 생성, 제거 등 담당할 예정
- MissionData : UI전용 미션 데이터
- NativeConstruct에서 미션 목록을 가져와서 띄움
- 위젯은 현재 블루프린트상에서 테스트용으로 로직이 존재함
---
> 🎉 add 미션 시스템 뼈대 제작, ✨ update 서브 미션 UI 임시 연결

- Source/AbyssDiverUnderWorld/DataRow/MissionDataRow/MissionBaseRow.h
- Source/AbyssDiverUnderWorld/Missions/AggroTriggerMission.cpp
- Source/AbyssDiverUnderWorld/Missions/AggroTriggerMission.h
- Source/AbyssDiverUnderWorld/Missions/InteractionMission.cpp
- Source/AbyssDiverUnderWorld/Missions/InteractionMission.h
- Source/AbyssDiverUnderWorld/Missions/ItemCollectionMission.cpp
- Source/AbyssDiverUnderWorld/Missions/ItemCollectionMission.h
- Source/AbyssDiverUnderWorld/Missions/ItemUseMission.cpp
- Source/AbyssDiverUnderWorld/Missions/ItemUseMission.h
- Source/AbyssDiverUnderWorld/Missions/KillMonsterMission.cpp
- Source/AbyssDiverUnderWorld/Missions/KillMonsterMission.h
- Source/AbyssDiverUnderWorld/Missions/MissionBase.h
- Source/AbyssDiverUnderWorld/Subsystems/MissionSubsystem.cpp
- Source/AbyssDiverUnderWorld/Subsystems/MissionSubsystem.h
---
- EMissionConditionType
- AtLeast : GoalCount 이상일 경우 조건 만족, AtMost : GoalCount 이하일 경우 조건 만족
-  EqualTo : GoalCount와 같은 경우 조건 만족, Custom : 자율
- RequestUnbinding - 바인딩된 델리게이트 해제용
---
> ✨ update  미션 조건 타입 설정 추가, 미션 서브시스템 이벤트 Unbind 추가

- Source/AbyssDiverUnderWorld/AbyssDiverUnderWorld.h
- Source/AbyssDiverUnderWorld/Character/UnitBase.h
- Source/AbyssDiverUnderWorld/DataRow/MissionDataRow/KillMonsterMissionRow.h
- Source/AbyssDiverUnderWorld/Missions/AggroTriggerMission.cpp
- Source/AbyssDiverUnderWorld/Missions/AggroTriggerMission.h
- Source/AbyssDiverUnderWorld/Missions/InteractionMission.cpp
- Source/AbyssDiverUnderWorld/Missions/InteractionMission.h
- Source/AbyssDiverUnderWorld/Missions/ItemCollectionMission.cpp
- Source/AbyssDiverUnderWorld/Missions/ItemCollectionMission.h
- Source/AbyssDiverUnderWorld/Missions/ItemUseMission.cpp
- Source/AbyssDiverUnderWorld/Missions/ItemUseMission.h
- Source/AbyssDiverUnderWorld/Missions/KillMonsterMission.cpp
- Source/AbyssDiverUnderWorld/Missions/KillMonsterMission.h
- Source/AbyssDiverUnderWorld/Missions/MissionBase.cpp
- Source/AbyssDiverUnderWorld/Missions/MissionBase.h
- Source/AbyssDiverUnderWorld/Subsystems/MissionSubsystem.cpp
- Source/AbyssDiverUnderWorld/Subsystems/MissionSubsystem.h
- Source/AbyssDiverUnderWorld/UI/MissionData.h
---
- UnitId 추가
- FKillMonsterMissionRow : UnitId 추가
- KillMonsterMission : UnitId추가, Unit 죽음 이벤트 로직 대략적으로 작성
- 미션 Init함수들 매개변수 미션 종류마다 다르게 받도록.....
- AbyssDiverUnderWorld : AbyssDiver 로그 경고 수준 최소치 Warning -> Log로 변경
---
> ✨ update UnitBase, Mission 서브시스템, ♻️ refactor Mission 서브시스템 및 기타

- Content/z3D_Radar/Materials/Basic_Glow_Mat.uasset
- Content/z3D_Radar/Materials/Fresnel_Glow_Mat.uasset
- Source/AbyssDiverUnderWorld/Interactable/OtherActors/Radars/Radar.cpp
- Source/AbyssDiverUnderWorld/Interactable/OtherActors/Radars/Radar.h
---
- 머티리얼의 Emissive를 적당히 조절하여 빛 번짐 현상을 완화 가능
- 다만 같은 맵이어도 장소에 따라 빛 번짐이 달라서 이 방식으론 완벽히 해결 불가능
---
> ✨ update 레이더 번짐 현상 완화를 위한 Emissive조절 기능 추가

- Source/AbyssDiverUnderWorld/Subsystems/SoundSubsystem.cpp
- Source/AbyssDiverUnderWorld/Subsystems/SoundSubsystem.h
---
- FadeIn으로 플레이 하기
- FadeOut으로 정지 시키기
- 현재 재생중인지 여부
- 해당 아이디의 오디오 길이 가져오기
---
> ✨ update  사운드 서브 시스템 기능 추가

- Content/_AbyssDiver/Blueprints/Environmental_Factors/BP_EventTrigger.uasset
- Content/_AbyssDiver/Blueprints/Environmental_Factors/BP_FogController.uasset
- Content/_AbyssDiver/Blueprints/Environmental_Factors/BP_Whale.uasset
- Source/AbyssDiverUnderWorld/Interactable/OtherActors/EventTriggers/EventTrigger.cpp
- Source/AbyssDiverUnderWorld/Interactable/OtherActors/EventTriggers/EventTrigger.h
- Source/AbyssDiverUnderWorld/Interface/Triggerable.h
---
- BeginOverlap, EndOverlap일 때 둘 다 발동하도록 수정
- Fog의 밀도를 조절해주는 액터
---
> ✨ update EventTrigger 발동 BeginOverlap, EndOverlap으로 분리, Triggerable 인터페이스 수정, 🎉 add FogController

- Content/Diver/Mesh/Dever_Epic_Full.uasset
- Content/Diver/Mesh/Dever_Epic_Full_Skeleton.uasset
- Source/AbyssDiverUnderWorld/Interactable/OtherActors/LevelSelector/LevelSelector.cpp
- Source/AbyssDiverUnderWorld/Interactable/OtherActors/LevelSelector/LevelSelector.h
- Source/AbyssDiverUnderWorld/Interactable/OtherActors/Tablet/ADTablet.cpp
- Source/AbyssDiverUnderWorld/UI/LevelSelectWidget.cpp
- Source/AbyssDiverUnderWorld/UI/LevelSelectWidget.h
---
Tablet
> BeginPlay에서 Getter에 대입하는것 수정
LevelSelectWidget
> MapName을 FName에서 Enum으로 변경
---
---
---
> [bugfix] 컴파일 에러 수정 [update] MapName 변경

- Source/AbyssDiverUnderWorld/UI/ChargeBatteryWidget.cpp
- Source/AbyssDiverUnderWorld/UI/ChargeBatteryWidget.h
---
- ChargeBatteryWidget 방어구문 추가
---
---
---
> ChargeBatteryWidget 방어구문 추가

- Source/AbyssDiverUnderWorld/Framework/ADCampGameMode.cpp
- Source/AbyssDiverUnderWorld/Framework/ADCampGameMode.h
---
캠프에서 GetMoney 치트 추가, ServerTravel 서버만 하도록 방어 코드 추가
---
> 캠프에서 GetMoney 치트 추가, ServerTravel 서버만 하도록 방어 코드 추가

- Source/AbyssDiverUnderWorld/Character/PlayerComponent/LanternComponent.cpp
---
- 현재 Detect Shape는 Server에만 존재하므로 Client에서 처리되지 않도록 수정
---
> BufFix: Non Authority 노드에서 Shape Update를 예외 처리

- Content/_AbyssDiver/Input/IA_Plyaer/IA_Inventory.uasset
- Content/_AbyssDiver/Input/IA_Plyaer/IA_Reload.uasset
- Source/AbyssDiverUnderWorld/Interactable/Item/Component/EquipUseComponent.cpp
- Source/AbyssDiverUnderWorld/Inventory/ADInventoryComponent.cpp
- Source/AbyssDiverUnderWorld/Inventory/ADInventoryComponent.h
- Source/AbyssDiverUnderWorld/UI/ChargeBatteryWidget.cpp
- Source/AbyssDiverUnderWorld/UI/ChargeBatteryWidget.h
- Source/AbyssDiverUnderWorld/UI/ToggleWidget.cpp
- Source/AbyssDiverUnderWorld/UI/ToggleWidget.h
---
- 인벤토리 위젯과 배터리 충전 위젯 show/hide 시 고장나는 문제 해결
---
---
---
> 인벤토리 위젯과 배터리 충전 위젯 show/hide 시 고장나는 문제 해결

- Content/_AbyssDiver/Blueprints/Interactables/Radars/BP_Radar.uasset
- Source/AbyssDiverUnderWorld/Interactable/OtherActors/Radars/Radar.cpp
---
- 범위는 기존 14 -> 20으로 변경
---
> ✨ update 레이더 높이 범위는 고려하지 않고 표시하도록 설정, 범위 변경

- Source/AbyssDiverUnderWorld/Shops/Shop.cpp
---
✨ update  인벤토리에 아이템 추가 실패할 경우 구매 실패 로직 추가
---
> ✨ update  인벤토리에 아이템 추가 실패할 경우 구매 실패 로직 추가

- Content/_AbyssDiver/Blueprints/UI/InteractableUI/WBP_InteractionDescriptionWidget.uasset
---
- 상호작용 UI 뜰 때 효과음 추가
---
---
---
> 상호작용 UI 뜰 때 효과음 추가

- Source/AbyssDiverUnderWorld/UI/SeaweedInteractiveActor.cpp
- Source/AbyssDiverUnderWorld/UI/SeaweedInteractiveActor.h
---
- int32 OverlappingCharacterCount를 추가해서 해초에 여러 플레이어 중 하나라도 있으면 계속 숙이기 유지하는 용도
- OnOverlapBegin() 부분에서 새로운 플레이어가 들어오면 카운터를 증가시킴(bShoundBlend를 true로 설정해 한명이라도 들어오면 숙이기 시작함
- OnOverlapEnd() 부분에서 플레이어가 해초 범위를 벗어났을 때 카운터를 감소시킴 -> 0이 되기 전까지는 절대 복원 안함
- UGameplayStatics::GetPlayerCharacter(GetWorld(), 0)에서 자기 자신만 기준으로 코드를 작성하였는데 otheractor로 판별하는 방식으로 수정
---
---
- 항상 감사함니다
---
> ✨ update: 멀티플레이 고려한 코드 수정

- Content/_AbyssDiver/Maps/Prototypes_Test/HGYTest/BP_HGYUnderwaterCharacter.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/HGYTest/BP_TestHGYGameMode.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/HGYTest/M_BrokenShield.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/HGYTest/M_Shield.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/HGYTest/M_ShieldUI.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/HGYTest/Shallow_HGY.umap
- Content/_AbyssDiver/Maps/Prototypes_Test/HGYTest/T_Crysis.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/HGYTest/WBP_Shield.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/HGYTest/broken.uasset
- Source/AbyssDiverUnderWorld/Inventory/ADInventoryComponent.cpp
---
- Ground에서 드래그 드랍 시 산소 스폰X
- DropLocation 위치 변경(잠수정에서 벽 근처에서 drop 시 벽 너머에 스폰되어서 가까이 스폰되도록 변경
- 배터리 사용한거 습득후 추가 배터리 습득했을 때 Amount 초기화되는 버그 해결
- shield 이펙트 추가(아직 연구중..)
---
---
---
> 버그 해결 및 추가 수정

- Content/_AbyssDiver/Blueprints/Boss/AlienShark/BP_AlienShark.uasset
- Content/_AbyssDiver/Blueprints/Boss/AlienShark/BT_MoreEnhanced_AlienShark.uasset
- Content/_AbyssDiver/Blueprints/Gimmic/SafeZone/BP_SafeZone.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/KDYTest/KDY_LineTracingTest.umap
- Source/AbyssDiverUnderWorld/Boss/Boss.cpp
- Source/AbyssDiverUnderWorld/Boss/EnhancedBossAIController.cpp
- Source/AbyssDiverUnderWorld/Boss/Task/AlienShark/BTTask_PerformChasing.cpp
- Source/AbyssDiverUnderWorld/Boss/Task/AlienShark/BTTask_PerformChasing.h
- Source/AbyssDiverUnderWorld/Boss/Task/AlienShark/BTTask_SetTargetLocation.cpp
---
- 상어의 시야각에 없을 때 숨으면 의심상태로 전이
- 수중생물의 회전각 감지 과정에서 후방까지 감지하도록 추가
---
> [Update] 해초에 숨었을 때에 대한 대응 상황 구현

- Content/_AbyssDiver/Blueprints/UI/Options/WBP_Options.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/HGYTest/BP_HGYUnderwaterCharacter.uasset
- Source/AbyssDiverUnderWorld/Inventory/ADInventoryComponent.cpp
- Source/AbyssDiverUnderWorld/Inventory/ADInventoryComponent.h
---
- 시작 메뉴 options ui 디자인 변경 및 애니메이션 추가
- 인벤토리 위젯 업데이트 문제 해결
---
---
---
> 레벨 이동 시 클라이언트 인벤토리 위젯 업데이트 누락 문제 해결

- Content/_AbyssDiver/Blueprints/Boss/AlienShark/AIC_EnhancedAilenShark.uasset
- Content/_AbyssDiver/Blueprints/Boss/AlienShark/BP_AlienShark.uasset
- Content/_AbyssDiver/Blueprints/Boss/AlienShark/BT_MoreEnhanced_AlienShark.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/KDYTest/KDY_LineTracingTest.umap
- Source/AbyssDiverUnderWorld/Boss/Boss.cpp
- Source/AbyssDiverUnderWorld/Boss/EnhancedBossAIController.cpp
- Source/AbyssDiverUnderWorld/Boss/EnhancedBossAIController.h
---
- 데미지, 피를 감지하는 경우 기본적으로 해당 플레이어를 추적하도록 변경
---
> [Update] AI Perception 수정

- Content/_AbyssDiver/DataTable/DT_Upgrade.uasset
- Source/AbyssDiverUnderWorld/Character/UnderwaterCharacter.cpp
- Source/AbyssDiverUnderWorld/Character/UnderwaterCharacter.h
---
- 랜턴 가시 거리 1.5배 증가
- ZoneSpeedMultiplier 적용 수정
---
> Update: Lantern 가시 거리 1.5배 증가, BugFix: ZoneSpeedMultiplier 적용 수정

- Source/AbyssDiverUnderWorld/Character/PlayerComponent/PlayerHUDComponent.cpp
- Source/AbyssDiverUnderWorld/Monster/Monster.cpp
- Source/AbyssDiverUnderWorld/Monster/MonsterAIController.cpp
---
[[Update] PlayerHUDComponent, Monster, MonsterAIController 코드에 방어로직 추가]
---
> [Update] PlayerHUDComponent, Monster, MonsterAIController 코드에 방어로직 추가

- Content/_AbyssDiver/Blueprints/Character/BP_UnderwaterCharacter.uasset
- Content/_AbyssDiver/Blueprints/Framework/BP_ADPlayerController.uasset
- Source/AbyssDiverUnderWorld/Framework/ADGameInstance.h
---
- 캐릭터가 WASD 키로 움직이도록 구현
- BP_PlayerInput 블루프린트 신규 생성
- 맵(BP_MainMap)에 시작 지점 추가
---
---
---
> 블루프린트 파일 깨진거 복구

- Source/AbyssDiverUnderWorld/Interactable/OtherActors/ADDroneSeller.cpp
> 🐛 bugfix 광물 판매가 일어나지 않고 돈만 오르는 현상 수정

- Source/AbyssDiverUnderWorld/Character/PlayerComponent/CombatEffectComponent.h
- Source/AbyssDiverUnderWorld/Character/UnderwaterCharacter.h
---
BugFix: Compile 오류 수정. Getter를 Public으로 변경
> BugFix: Compile 오류 수정. Getter를 Public으로 변경

- Content/_AbyssDiver/Blueprints/Interactables/Seaweed/Seaweed_006_Physics1.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/YSE.umap
- Source/AbyssDiverUnderWorld/Interactable/OtherActors/ADDroneSeller.cpp
- Source/AbyssDiverUnderWorld/Interactable/Seaweed/SeaweedInteractiveActor.cpp
- Source/AbyssDiverUnderWorld/Interactable/Seaweed/SeaweedInteractiveActor.h
---
- 해초는 현재 constrains 값을 계속 수정하면서 진행 중입니다
- 원래 구현 방식이 광물 제출 전 빨간색 -> 목표치 완료하면 초록색이었는데 광물 제출할 때마다 드론이 초록색으로 잠시 바뀌고 목표 금액보다 적으면 다시 빨간색으로 유지하고 달성하면 초록색으로 바뀌는 것으로 수정했습니다!
---
---
- stashed changes에서 restore 누르면 droneseller 코드만 뜨는데 혹시 해결방법을 아시나용...
---
> ✨ update: 해초 수정 중 & 드론 제출 시 초록색으로 잠시 바뀌기 수정

- Source/AbyssDiverUnderWorld/Interactable/OtherActors/ADDroneSeller.cpp
- Source/AbyssDiverUnderWorld/Interactable/OtherActors/ADDroneSeller.h
---
- 멀티플레이 환경(리슨 서버)에서도 해당 색상 변경 연출이 모든 클라이언트에 반영되도록 NetMulticast 함수로 처리
- `Multicast_TemporarilyHighlightGreen(bool bReachedGoal)` 함수 구현, 
- 제출 시 즉시 초록색 → 0.5초 후 목표 달성 여부에 따라 초록/빨강으로 전환
- 기존 `SetLightColor()` 방식은 유지하되, 일시 변경 연출에 추가 활용
---
---
- 감사함니다
---
> ✨ update: 드론 셀러 제출 시 색상 변경 연출 멀티플레이어 대응

- Source/AbyssDiverUnderWorld/Boss/BossAIController.cpp
> [Bugfix] 안 쓰는 변수 제거

- Content/_AbyssDiver/Blueprints/UI/Options/WBP_Options.uasset
- Content/_AbyssDiver/Blueprints/UI/Options/WBP_Options_Audio.uasset
- Source/AbyssDiverUnderWorld/Framework/ADSettingsSaveGame.cpp
- Source/AbyssDiverUnderWorld/Framework/ADSettingsSaveGame.h
- Source/AbyssDiverUnderWorld/Framework/SettingsManager.cpp
- Source/AbyssDiverUnderWorld/Framework/SettingsManager.h
---
- 오디오 세팅 설정하고 Apply 누르면 저장 됨. 
---
> ✨ update 사운드 세팅 저장 기능 완성

- Source/AbyssDiverUnderWorld/Boss/Kraken/Kraken.cpp
- Source/AbyssDiverUnderWorld/UI/CurrentZone.cpp
> 🐛 bugfix 패키징 버그 수정

- Content/Diver/Mesh/Dever_Epic_Full.uasset
- Content/Diver/Mesh/Dever_Epic_Full_Skeleton.uasset
- Content/FlareGun/Flaregun.uasset
- Content/FlareGun/Flaregun3.uasset
- Content/FlareGun/SKM_flaregun3.uasset
- Content/_AbyssDiver/Blueprints/Interactables/Item/Minerals/BP_Chromite.uasset
- Content/_AbyssDiver/Blueprints/Interactables/Item/Minerals/BP_CobaltShell.uasset
- Content/_AbyssDiver/Blueprints/Interactables/Item/Minerals/BP_LostRune.uasset
- Content/_AbyssDiver/Blueprints/Interactables/Item/Minerals/BP_MagneticCrystal.uasset
- Content/_AbyssDiver/Blueprints/Interactables/Item/Minerals/BP_QuantumCore.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/CWSTest/CWS.umap
- Source/AbyssDiverUnderWorld/Interactable/Item/ADOreRock.cpp
- Source/AbyssDiverUnderWorld/Interactable/Item/Component/ADInteractableComponent.h
- Source/AbyssDiverUnderWorld/Interactable/Item/Component/ADInteractionComponent.cpp
- Source/AbyssDiverUnderWorld/Interactable/Item/Component/ADInteractionComponent.h
- Source/AbyssDiverUnderWorld/Interactable/Item/Component/EquipUseComponent.cpp
- Source/AbyssDiverUnderWorld/Inventory/ADInventoryComponent.cpp
- Source/AbyssDiverUnderWorld/Inventory/ADInventoryComponent.h
---
> 광물들 크기 1.5배 증가
> 플레어건 머터리얼 발광 효과 추가 (어두운 환경에서도 잘 보이게)
> 채광 가능한 암석 하이라이트 로직 변경 (Overlap만 되어도 하이라이트)
> 아이템을 장착한 상태에서 채광 시 버그 생기던 것 개선
> DPV 작동 안하던 것 개선
---
---
---
> [update] 광물 크기 키우기, [Bugfix] DPV, 채광 버그 수정

- Content/_AbyssDiver/Blueprints/Projectile/BP_ADSpearGunBullet.uasset
- Content/_AbyssDiver/Blueprints/UI/UI/WBP_PlayerStatusWidget.uasset
- Source/AbyssDiverUnderWorld/Projectile/ADSpearGunBullet.cpp
- Source/AbyssDiverUnderWorld/Projectile/PoolableItem.cpp
- Source/AbyssDiverUnderWorld/UI/PlayerStatusWidget.cpp
- Source/AbyssDiverUnderWorld/UI/PlayerStatusWidget.h
---
- 작살 콜리전 문제 해결
- hit effect 체력과 연결
---
---
---
> 작살 콜리전 문제 해결 및 hit screen effect 체력과 연결

- Source/AbyssDiverUnderWorld/Boss/EyeStalker/EyeStalkerAIController.cpp
- Source/AbyssDiverUnderWorld/Boss/EyeStalker/EyeStalkerAIController.h
- Source/AbyssDiverUnderWorld/Boss/Task/EyeStalker/BTService_ApplyDamageToPlayer.cpp
- Source/AbyssDiverUnderWorld/Boss/Task/EyeStalker/BTTask_EyeStalkerAttack.cpp
- Source/AbyssDiverUnderWorld/Boss/Task/EyeStalker/BTTask_EyeStalkerAttack.h
- Source/AbyssDiverUnderWorld/Boss/Task/EyeStalker/BTTask_EyeStalkerDetected.cpp
- Source/AbyssDiverUnderWorld/Gimmic/Spawn/SpawnManager.cpp
---
- 클라이언트에서 스폰 로직이 호출 안 되도록 수정
- EyeStalker에게 감시당할 시 Vignette 효과 적용
---
> [Update] EyeStalker Vignette 효과 및 스폰 버그 수정

- Source/AbyssDiverUnderWorld/Projectile/ADSpearGunBullet.cpp
---
- 작살 커지는 문제 해결
---
---
테스트는 안 해봐서 혹시 이걸로 해결안되면 부탁드립니다..!
---
> [bugfix] 작살 커지는 문제 해결

- Content/_AbyssDiver/Blueprints/UI/UI/WBP_PlayerStatusWidget.uasset
- Content/_AbyssDiver/Maps/Final/Level/Submarine_Lobby.umap
---
- 부활 후 나침반 작동 하지 않음 -> 유효하지 않으면 다시 Set해서 사용하는 로직 추가
---
> 🐛 bugfix 부활 후 나침반 작동 하지 않음 ✨ update 캠프 상점 문 작동 추가

- Source/AbyssDiverUnderWorld/Interactable/OtherActors/Radars/Radar.cpp
- Source/AbyssDiverUnderWorld/Projectile/ADSpearGunBullet.cpp
---
- 작살 커지는 현상 : Deactivate될 때 Scale 1,1,1로 초기화
- 레이더 비활성화 : 단순 nullptr 체크에서 Valid체크로 변경
---
> 🐛 bugfix 작살 커지는 현상, 레이더 비활성화 늦게 되는 현상,

- Source/AbyssDiverUnderWorld/Character/PlayerComponent/PlayerHUDComponent.cpp
- Source/AbyssDiverUnderWorld/Character/PlayerComponent/PlayerHUDComponent.h
---
- 🐛 bugfix 맵 이동시 크래시 : Hud가 존재하지 않는 플레이어 캐릭터에도 함수가 호출되었음 Multicast여서
---
> 🐛 bugfix 맵 이동시 크래시

- Source/AbyssDiverUnderWorld/Interactable/Item/Component/EquipUseComponent.cpp
- Source/AbyssDiverUnderWorld/Interactable/OtherActors/Level/SelectMachine.cpp
---
- 호스트가 아닌 클라이언트가 접근한 후 멀어져도 SelectMachine이 종료되는 현상
- 방어 코드 추가, 코드 약간 정리
---
> 🐛 bugfix SelectMachine, ♻️ refactor EquipUseComponent

- Source/AbyssDiverUnderWorld/Interactable/OtherActors/Portals/Portal.cpp
- Source/AbyssDiverUnderWorld/Interactable/OtherActors/Portals/Portal.h
- Source/AbyssDiverUnderWorld/Interactable/OtherActors/Portals/PortalToSubmarine.cpp
- Source/AbyssDiverUnderWorld/Interactable/OtherActors/Portals/PortalToSubmarine.h
- Source/AbyssDiverUnderWorld/UI/PlayerStatusWidget.cpp
- Source/AbyssDiverUnderWorld/UI/TargetIndicatorWidget.cpp
---
- 기타 : 컴파일 Warning 해결, Log Verbosity 변경
---
> ✨ update 잠수정으로 돌아가는 포탈 시체를 묶었을 경우 같이 들어가도록 변경 및 기타

- Source/AbyssDiverUnderWorld/Boss/EyeStalker/EyeStalkerAIController.cpp
- Source/AbyssDiverUnderWorld/Boss/EyeStalker/EyeStalkerAIController.h
---
- 다른 EyeStalker가 공격 중일 때 플레이어가 시야에서 벗어나는 경우
해당 플레이어의 EyeStalker 공격 플래그 초기화 추가
---
> [BugFix] EyeStalker 공격 버그 수정

- Source/AbyssDiverUnderWorld/Boss/Boss.cpp
- Source/AbyssDiverUnderWorld/Boss/Boss.h
- Source/AbyssDiverUnderWorld/Boss/Kraken/Kraken.cpp
> [Refactoring] Boss, Kraken

- Source/AbyssDiverUnderWorld/Boss/AlienShark/AlienShark.h
---
- AlienShark 클래스의 사용하지 않는 변수 제거
---
> [Del] 사용하지 않는 변수 제거

- Content/_AbyssDiver/Blueprints/Boss/AlienShark/BP_AlienShark.uasset
- Content/_AbyssDiver/Blueprints/Boss/Blowfish/BP_Blowfish.uasset
- Content/_AbyssDiver/Blueprints/Boss/Kraken/BP_Kraken.uasset
- Content/_AbyssDiver/Blueprints/Boss/Limadon/BP_Limadon.uasset
- Content/_AbyssDiver/Blueprints/Boss/SeaObserver/BP_SeaObserver.uasset
- Content/_AbyssDiver/Blueprints/Boss/Serpmare/BP_Big_Serpmare.uasset
- Content/_AbyssDiver/Blueprints/Boss/Serpmare/BP_Serpmare.uasset
> [Update] AI Animation 설정

- Content/_AbyssDiver/DataTable/SoundData/DT_SFX.uasset
- Source/AbyssDiverUnderWorld/Character/PlayerComponent/CombatEffectComponent.cpp
- Source/AbyssDiverUnderWorld/Character/PlayerComponent/ShieldComponent.cpp
- Source/AbyssDiverUnderWorld/Framework/ADPlayerController.cpp
- Source/AbyssDiverUnderWorld/Framework/ADPlayerController.h
---
- 실드 이펙트가 재생되지 않는 오류 수정
- Gain Shield 명령어 추가
- Shield Broken Sound 지정
---
> BugFix: 실드 이펙트가 재생되지 않는 오류 수정

- Source/AbyssDiverUnderWorld/Character/ADSpectatorPawn.cpp
- Source/AbyssDiverUnderWorld/Character/ADSpectatorPawn.h
- Source/AbyssDiverUnderWorld/Character/PlayerHUDWidget.cpp
- Source/AbyssDiverUnderWorld/Character/PlayerHUDWidget.h
- Source/AbyssDiverUnderWorld/Character/UnderwaterCharacter.cpp
- Source/AbyssDiverUnderWorld/Character/UnderwaterCharacter.h
- Source/AbyssDiverUnderWorld/Framework/ADInGameMode.cpp
- Source/AbyssDiverUnderWorld/Framework/ADInGameMode.h
- Source/AbyssDiverUnderWorld/Framework/ADPlayerState.cpp
- Source/AbyssDiverUnderWorld/Framework/ADPlayerState.h
---
- Add: Player State에 캐릭터 현재 생존 상태 저장
- Update: Underwater Character Change State Delegate 변경
---
> Add: Player State에 캐릭터 현재 생존 상태 저장, Update: Underwater Character Change State Delegate 변경

- Content/_AbyssDiver/Blueprints/Framework/BP_ADCampGameMode.uasset
- Content/_AbyssDiver/Blueprints/Framework/BP_ADGameInstance.uasset
- Source/AbyssDiverUnderWorld/Framework/ADCampGameMode.cpp
- Source/AbyssDiverUnderWorld/Framework/ADCampGameMode.h
- Source/AbyssDiverUnderWorld/Framework/ADGameInstance.cpp
- Source/AbyssDiverUnderWorld/Framework/ADGameInstance.h
- Source/AbyssDiverUnderWorld/Framework/ADInGameMode.cpp
- Source/AbyssDiverUnderWorld/Framework/ADPlayerController.cpp
- Source/AbyssDiverUnderWorld/Framework/ADPlayerController.h
---
- 초기 지원금은 BP_ADCampGameMode에서 InitialSupportMoney를 수정하면 된다
---
> 🐛 bugfix 클라이언트에서 패배 사운드 재생 안 됨 ✨ update  초기 지원금 기능 추가

- Source/AbyssDiverUnderWorld/Shops/Shop.cpp
- Source/AbyssDiverUnderWorld/Shops/Shop.h
- Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopItemSlotWidget.cpp
- Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopItemSlotWidget.h
---
- 상점 아이템 더블클릭시 장바구니에 추가, 업그레이드는 바로 구매
---
> ✨ update 상점 더블 클릭 기능 추가

- Source/AbyssDiverUnderWorld/Interactable/Item/ADExchangeableItem.cpp
---
- DynamicMaterial에 Valid 체크 추가
---
---
---
> [update] ADExchangeableItem : DynamicMaterial Valid 체크 추가

- Content/_AbyssDiver/Maps/Prototypes_Test/DeepAbyss.umap
- Content/_AbyssDiver/Maps/Prototypes_Test/KY/BP_LevelTraveler.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/YWC/Shallow_Test.umap
- Source/AbyssDiverUnderWorld/Interactable/OtherActors/Radars/Radar.cpp
---
- LevelTraveler : 문 모양으로 변경
- Radar : Mesh, Material쪽 Valid 체크
---
> ✨ update LevelTraveler 메쉬 변경, 🐛 bugfix Radar 방어 코드 추가

- Content/_AbyssDiver/Blueprints/Boss/EyeStalker/AIC_EyeStalker.uasset
- Content/_AbyssDiver/Blueprints/Boss/Limadon/BP_Limadon.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/KDYTest/KDY_LineTracingTest.umap
- Source/AbyssDiverUnderWorld/Boss/Boss.h
- Source/AbyssDiverUnderWorld/Boss/EyeStalker/EyeStalkerAIController.cpp
- Source/AbyssDiverUnderWorld/Boss/Task/EyeStalker/BTTask_EyeStalkerAttack.cpp
- Source/AbyssDiverUnderWorld/Boss/Task/EyeStalker/BTTask_EyeStalkerDetected.cpp
- Source/AbyssDiverUnderWorld/Boss/Task/EyeStalker/BTTask_EyeStalkerIdle.cpp
---
- Limadon 공격 안 하는 버그 수정
- EyeStalker 타겟 초기화 안 되는 버그 수정
> [BugFix] Limadon, EyeStalker

- Source/AbyssDiverUnderWorld/Shops/Shop.cpp
---
- 상점 이용 도중 레벨 이동시 크래시 버그방지
---
> 🐛 bugfix 상점 방어 코드 추가

- Source/AbyssDiverUnderWorld/Character/UnderwaterCharacter.cpp
---
- 클라이언트에서 채집을 끝난 후에도 캐릭터의 채집기가 없어지지 않는 버그 개선
---
---
---
> [bugfix] 레이저채집기 버그 개선

- Source/AbyssDiverUnderWorld/Framework/ADCampGameMode.cpp
- Source/AbyssDiverUnderWorld/Framework/ADCampGameMode.h
- Source/AbyssDiverUnderWorld/Subsystems/SaveDataSubsystem.cpp
- Source/AbyssDiverUnderWorld/Subsystems/SaveDataSubsystem.h
---
- 게임 로드 중이거나 세이브 중일 경우 레벨 이동 막음
- 게임 로드가 끝나면 레벨 재시작
- 레벨 이동 중이면 세이브, 로드를 막음
---
> ✨ update  안전 코드 추가, 로드시 레벨 재시작

- Source/AbyssDiverUnderWorld/Interactable/OtherActors/Radars/Radar2DComponent.cpp
- Source/AbyssDiverUnderWorld/UI/RadarWidgets/Radar2DWidget.cpp
- Source/AbyssDiverUnderWorld/UI/RadarWidgets/Radar2DWidget.h
---
- 유효하지 않는 리런을 제대로 제거해주지 않아서 생김
---
> 🐛 bugfix 간헐적으로 레이더 표시되지 않는 현상, 레이더 리턴이 계속 남아있는 현상

- Content/_AbyssDiver/Blueprints/Boss/AlienShark/BB_AlienShark.uasset
- Content/_AbyssDiver/Blueprints/Boss/AlienShark/BT_MoreEnhanced_AlienShark.uasset
- Source/AbyssDiverUnderWorld/Boss/Boss.cpp
- Source/AbyssDiverUnderWorld/Boss/Boss.h
- Source/AbyssDiverUnderWorld/Boss/EnhancedBossAIController.cpp
- Source/AbyssDiverUnderWorld/Boss/Task/AlienShark/BTService_CheckOnNavMesh.cpp
- Source/AbyssDiverUnderWorld/Boss/Task/AlienShark/BTService_CheckOnNavMesh.h
- Source/AbyssDiverUnderWorld/Boss/Task/AlienShark/BTService_HasObstacleAhead.cpp
- Source/AbyssDiverUnderWorld/Boss/Task/AlienShark/BTService_HasObstacleAhead.h
- Source/AbyssDiverUnderWorld/Boss/Task/AlienShark/BTTask_PerformChasing.cpp
- Source/AbyssDiverUnderWorld/Boss/Task/AlienShark/BTTask_PerformTurn.cpp
- Source/AbyssDiverUnderWorld/Boss/Task/AlienShark/BTTask_PerformTurn.h
- Source/AbyssDiverUnderWorld/Boss/Task/AlienShark/BTTask_ReturnToNavMeshArea.cpp
- Source/AbyssDiverUnderWorld/Boss/Task/AlienShark/BTTask_ReturnToNavMeshArea.h
- Source/AbyssDiverUnderWorld/Boss/Task/AlienShark/BTTask_RotationAlongSurface.cpp
- Source/AbyssDiverUnderWorld/Boss/Task/AlienShark/BTTask_StartTurn.cpp
- Source/AbyssDiverUnderWorld/Boss/Task/AlienShark/BTTask_StartTurn.h
- Source/AbyssDiverUnderWorld/Outsourced/AquaticMovementComponent.cpp
- Source/AbyssDiverUnderWorld/Outsourced/AquaticMovementComponent.h
AquaticMovementComponent의 InitializeComponent 함수 InitComponent로 이름 변경 -> 기존 언리얼의 함수 이름과 겹침
> ♻️ refactor Deprecated 전부 주석처리 및 삭제 및 기타

- Source/AbyssDiverUnderWorld/Monster/Components/TickControlComponent.cpp
- Source/AbyssDiverUnderWorld/Monster/Components/TickControlComponent.h
---
- 우선 몬스터에게 사용할 용도로 만들었으나 필요할 경우 다른 곳에도 적용 가능
- RegisterComponent 함수로 원하는 컴포넌트를 등록하면 그 컴포넌트의 틱을 설정에 맞춰 최적화로 작동
- 최적화 세부 내용
- 거리에 따른 틱 Interval 조절
- 카메라 시야에 따른 틱 Interval 조절
- 장애물 여부도 고려하여 틱 Interval 조절
---
> 🎉 add TickControlComponent - 틱 최적화 컴포넌트

- Content/Limadon/Animations/AM_Limadon_Appear.uasset
- Content/Limadon/Animations/AM_Limadon_Spit.uasset
- Content/_AbyssDiver/Blueprints/Boss/Limadon/BT_Limadon.uasset
- Content/_AbyssDiver/Blueprints/Boss/SeaObserver/BB_SeaObserver.uasset
- Content/_AbyssDiver/Blueprints/Boss/SeaObserver/BP_SeaObserverAIController.uasset
- Content/_AbyssDiver/Blueprints/Boss/SeaObserver/BP_SeaObserverAIController_Lagacy.uasset
- Content/_AbyssDiver/Blueprints/Boss/SeaObserver/BT_SeaObserver.uasset
- Content/_AbyssDiver/Blueprints/Boss/SeaObserver/BT_SeaObserver_Lagacy.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/HSRTest/HSR_Test2.umap
- Source/AbyssDiverUnderWorld/Monster/AnimNotify/AnimNotify_ChangeMonsterState.cpp
- Source/AbyssDiverUnderWorld/Monster/AnimNotify/AnimNotify_ChangeMonsterState.h
- Source/AbyssDiverUnderWorld/Monster/Boss/Blowfish/Blowfish.h
- Source/AbyssDiverUnderWorld/Monster/Boss/Limadon/Limadon.h
- Source/AbyssDiverUnderWorld/Monster/Boss/SeaObserver/SeaObserver.cpp
- Source/AbyssDiverUnderWorld/Monster/Boss/SeaObserver/SeaObserver.h
---
- 기존 AnimNotify_ChangeBossState 대체용
- Monster 클래스 전용
---
> ♻️ refactor Blowfish, Limadon, SeaObserver -> monster 상속 받도록 변경, 🎉 add AnimNotify_ChangeMonsterState

- Content/Serpmare/Animations/AM_Serpmare_Appear.uasset
- Content/Serpmare/Animations/AM_Serpmare_Attack.uasset
- Content/Serpmare/Animations/AM_Serpmare_Disappear.uasset
- Content/_AbyssDiver/Blueprints/Boss/Serpmare/BB_Serpmare.uasset
- Content/_AbyssDiver/Blueprints/Boss/Serpmare/BT_Big_Serpmare.uasset
- Content/_AbyssDiver/Blueprints/Boss/Serpmare/BT_Serpmare.uasset
- Content/_AbyssDiver/Maps/Prototypes_Test/HSRTest/HSR_Test2.umap
- Source/AbyssDiverUnderWorld/Monster/Boss/Serpmare/Serpmare.cpp
- Source/AbyssDiverUnderWorld/Monster/Boss/Serpmare/Serpmare.h
- Source/AbyssDiverUnderWorld/Monster/Monster.cpp
- Source/AbyssDiverUnderWorld/Monster/Monster.h
---
- BB_Serpmare : 사용하지 않는 BossState 삭제
- BT_Big_Serpmare, BT_Serpmare : 데코레이터 이름 변경
- AM_Serpmare_Appear, AM_Serpmare_Attack, AM_Serpmare_Disappear : AnimNotify_ChangeMonsterState 사용으로 변경
- Serpmare.cpp : AddDetection, RemoveDetection 재정의
- Beginplay : ApplyMonsterStateChange(EMonsterState::Patrol); 삭제
- AddDetection, RemoveDetection 가상 함수로 변경
---
> ♻️ refactor Serpmare Monster 상속 받도록 변경 및 기타

- Source/AbyssDiverUnderWorld/Framework/ADTutorialGameMode.cpp
---
- 시체 반납 드론 튜토리얼 루프 알람 누락 수정
---
---
---
> 시체 반납 드론 튜토리얼 루프 알람 누락 수정
