NbcampUnreal/1st-Team2-Final-Project

AbyssDiverUnderWorld.uproject
Content/_AbyssDiver/Blueprints/UI/ShopUI/WBP_ElementInfoPanel.uasset
Content/_AbyssDiver/Blueprints/UI/ShopUI/WBP_Shop.uasset
Content/_AbyssDiver/Blueprints/UI/ShopUI/WBP_ShopCategoryTap.uasset
Content/_AbyssDiver/Blueprints/UI/ShopUI/WBP_ShopItemSlot.uasset
Content/_AbyssDiver/M_SciFi_Octopuse_Body_Skin1.uasset
Content/_AbyssDiver/Maps/Prototypes_Test/HSRTest/BP_TestShop.uasset
Content/_AbyssDiver/Maps/Prototypes_Test/HSRTest/DT_Test.uasset
Content/_AbyssDiver/Maps/Prototypes_Test/HSRTest/HSR_Test.umap
Source/AbyssDiverUnderWorld/Shops/Shop.cpp
Source/AbyssDiverUnderWorld/Shops/Shop.h
Source/AbyssDiverUnderWorld/Shops/ShopItemEntryData.cpp
Source/AbyssDiverUnderWorld/Shops/ShopItemEntryData.h
Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopCategoryTabWidget.cpp
Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopCategoryTabWidget.h
Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopItemSlotWidget.cpp
Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopItemSlotWidget.h
Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopTileView.cpp
Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopTileView.h
Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopWidget.cpp
Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopWidget.h

---
- 탭 전환 버튼 (소비, 장비 탭 등등)
- Entry 역할, TileView에 띄우는 타일
- 상점 아이템 목록을 TileView로 구현
- 상점 Widget 총괄
- Entry 데이터를 받고 위젯 새로고침 역할
- 상점이 가지는 아이템 Id 정보를 관리
- 상점 Widget에게 알맞게 명령
- Fast Array Serializer로 아이디 배열 최적화
- 상점 아이템 슬롯에 띄울 정보 전달용
---
참고로 아이템 이름 적혀있는거 ToolTip 자리인데 일단 임시로 띄워둠
완성되면 마우스 올릴 때 추기정보 표시
---
- 양이 좀 많습니다 ㅈㅅ..
---

상점 데이터 동기화, 탭 전환 기능 구현

---

Config/DefaultEngine.ini
Content/_AbyssDiver/Blueprints/Core/BP_TestGameInstance.uasset
Source/AbyssDiverUnderWorld/Character/UnderwaterCharacter.cpp
Source/AbyssDiverUnderWorld/Subsystems/ADTestGameInstance.h
Source/AbyssDiverUnderWorld/Subsystems/DataTableSubsystem.cpp

---
- 수중 캐릭터의 Gravity Scale을 0으로 수정([Feat] 캐릭터 중력 비활성화 요청 #48)
- DataTableSubsystem 예외 처리 추가
- DataTable을 지정 안 했을 떄 크래시 나는 현상 방지
- BP_TestGameInstance 추가
DataTableSubsystem은 큰 틀만 잡고 세부 작업은 나중에 할려고 했는데 현재 커밋에서 크래시가 발생하는 현상이 있었습니다. 해당 부분만 수정해서 문제 없는 상황으로 수정했고 자세한 로직은 추후에 보완될 예정입니다.
Game Instance 또한 추후에 ADGameInstance가 들어오면 대체될 예정입니다.
---
---
---

Character Gravity 조정, DataTableSubsystem 예외 처리 및 BP 설정

---

Content/_AbyssDiver/Blueprints/UI/ShopUI/WBP_ElementInfoPanel.uasset
Content/_AbyssDiver/Blueprints/UI/ShopUI/WBP_Shop.uasset
Content/_AbyssDiver/Blueprints/UI/ShopUI/WBP_ShopItemMeshPanel.uasset
Content/_AbyssDiver/Blueprints/UI/ShopUI/WBP_ShopItemSlot.uasset
Content/_AbyssDiver/Blueprints/UI/ShopUI/WBP_ShopUpgradeSlot.uasset
Content/_AbyssDiver/Maps/Prototypes_Test/HSRTest/BP_HSRTestUnderWaterCharacter.uasset
Source/AbyssDiverUnderWorld/Character/UpgradeComponent.cpp
Source/AbyssDiverUnderWorld/Character/UpgradeComponent.h
Source/AbyssDiverUnderWorld/Framework/ADPlayerState.cpp
Source/AbyssDiverUnderWorld/Framework/ADPlayerState.h
Source/AbyssDiverUnderWorld/Shops/Shop.cpp
Source/AbyssDiverUnderWorld/Shops/Shop.h
Source/AbyssDiverUnderWorld/Shops/ShopItemEntryData.h
Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopCategoryTabWidget.cpp
Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopElementInfoWidget.cpp
Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopElementInfoWidget.h
Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopItemMeshPanel.cpp
Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopItemMeshPanel.h
Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopItemSlotWidget.cpp
Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopWidget.cpp
Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopWidget.h

---
- UpgradeComponent - 클라이언트의 업그레이드 요청을 받아서 처리하고 다시 클라이언트에게 알림
- 업그레이드 클릭 후 구매 버튼을 누르면 UpgradeComponent를 통해 서버 RPC 호출
- ADPlayerState - UpgradeComponent 소유
- 상점에 Item Mesh 드래그로 회전시키는 로직 밑작업
---
---

✨ update 상점 업그레이드시 적용 로직 완성 및 기타

---

Content/_AbyssDiver/Blueprints/UI/ShopUI/WBP_ElementInfoPanel.uasset
Content/_AbyssDiver/Blueprints/UI/ShopUI/WBP_Shop.uasset
Content/_AbyssDiver/Maps/Prototypes_Test/HSRTest/BP_TestShop.uasset
Source/AbyssDiverUnderWorld/Shops/Shop.cpp
Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopElementInfoWidget.cpp
Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopElementInfoWidget.h
Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopItemMeshPanel.cpp
Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopItemMeshPanel.h
Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopWidget.cpp
Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopWidget.h

---
- 아이템 클릭 후 메쉬 패널에서 드래그하면 좌 우로 회전.
- 상점 열면 UIOnly 인풋 모드로 되도록 변경
---

✨ update 상점 아이템 메쉬 돌리기 기능 완성 및 기타

---

Source/AbyssDiverUnderWorld/Shops/Shop.cpp

---
- 이동 인풋을 유지한 채로 상점을 열면 그 방향으로 계속 이동을 하던 현상 수정
---

🐛 bugfix 상점 열고 이동 인풋이 유지되는 현상 수정

---

Source/AbyssDiverUnderWorld/Character/UnderwaterCharacter.cpp

---
- Upgrade 상태에서 BaseSpeed를 계산하는 방법이 잘못된 버그 수정
- BaseSpeed = 400 + UpgradeFactor
- Host의 Player가 Upgrade 정보를 초기화하지 않는 오류
- Upgrade Component 초기화 시점이 BeginPlay이고 Upgrade 정보 적용이 PossessedBy이기 때문에 Upgrade Component의 초기화 시점이 늦고 있습니다.
태스팅을 위해서 Upgrade Component  적용 부분만 수정하고 초기화 부분은 추후 수정하겠습니다.
---
---
---

BugFix: BaseSpeed 속도 적용이 잘못되어 있는 오류 수정

---

Content/_AbyssDiver/Blueprints/UI/InGameUI/WBP_LoadingScreen.uasset
Content/_AbyssDiver/Maps/Prototypes_Test/HSRTest/BP_TestShop.uasset
Content/_AbyssDiver/Maps/Prototypes_Test/KY/TestTransitionMap.umap
Source/AbyssDiverUnderWorld/Framework/ADInGameState.cpp
Source/AbyssDiverUnderWorld/Framework/ADInGameState.h
Source/AbyssDiverUnderWorld/Shops/Shop.cpp
Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopElementInfoWidget.cpp
Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopElementInfoWidget.h
Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopWidget.cpp
Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopWidget.h

- 초기 상점 탭은 장비창으로 고정
- 장비는 1개씩 구매하도록 설정
- 클라이언트에서 미리 돈 체크 후 구매 시도
- ADInGameState : UI 갱신용 델리게이트 선언
- TeamCreditsChangedDelegate, CurrentPhaseChangedDelegate, CurrentPhaseGoalChangedDelegate
- 현재 패키징시 상점 버그 있음
- 특정 플레이어 상점 UI 갱신 안 됨, 이후 튕김
- 여러개 구매해도 1개 분량의 돈 감소
- 상점 UI 개수 표시 버그 - 최대량이 소지금보다 더 많게 설정 가능, 0개 가능
---

상점 아이템 구매시 돈 차감, 상점 UI 갱신, 임시 Traansition 맵에 로딩 위젯 생성 및 기타

---

Source/AbyssDiverUnderWorld/Shops/Shop.cpp
Source/AbyssDiverUnderWorld/Shops/Shop.h
Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopElementInfoWidget.cpp
Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopElementInfoWidget.h
Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopTileView.cpp

---
- 아이템 다량 구매해도 1개분량 만큼만 돈이 차감되는 현상 수정
- 아이템 수량 조절 버그 수정
- 업그레이드 탭 누르면 크래시 나는 버그 수정
- 상점용 로그 카테고리 선언, 상점 버그 디버깅용
- 아직 클라이언트에서 상점 버그 일어나는 조건도 모름..
---

🐛 bugfix 상점 버그 해결 및 기타

---

Content/_AbyssDiver/Maps/Prototypes_Test/HSRTest/BP_TestShop.uasset
Content/_AbyssDiver/Maps/Prototypes_Test/HSRTest/HSR_Test.umap
Source/AbyssDiverUnderWorld/Framework/ADInGameState.cpp
Source/AbyssDiverUnderWorld/Shops/Shop.cpp
Source/AbyssDiverUnderWorld/Shops/Shop.h

---
- Render Target으로 그리는 메쉬가 생각보다 너무 많은 성능저하를 일으켜서 최적화
- 상점을 열었을 때만 Render Target 활성화로 변경
- 우선 메쉬에 적용되는 각종 효과는 제거, 후에 효과 적용 예정
---

상점 아이템 프리뷰 메쉬 최적화

---

Content/_AbyssDiver/Maps/Prototypes_Test/HSRTest/BP_TestShop.uasset
Content/_AbyssDiver/Maps/Prototypes_Test/HSRTest/HSR_Test.umap
Source/AbyssDiverUnderWorld/Shops/Shop.cpp
Source/AbyssDiverUnderWorld/Shops/Shop.h
Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopWidget.cpp
Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopWidget.h

---
- 상점의 아이템 프리뷰 메쉬가 주변의 라이트 환경에 영향을 받지 않도록 독자적 채널을 사용 -> 2번
- 아이템 프리뷰 메쉬 전용 라이트 추가 - PointLight
- 최적화를 위해 컴포넌트 모빌리티 Static으로 설정
- ShopWidget : 일부 레벨에서 NativeOnInitialized가 발동 되지 않아서 델리게이트용으로 NativeConstruct, NativeDestruct 추가
---

✨ update 상점 전용 라이트 추가 및 기타

---

Content/_AbyssDiver/Blueprints/ABP/Player/ABP_Underwater.uasset
Content/_AbyssDiver/Maps/Prototypes_Test/KKS/KKS_LocomotionTest.umap
Source/AbyssDiverUnderWorld/Character/UnderwaterAnimInstance.cpp
Source/AbyssDiverUnderWorld/Character/UnderwaterAnimInstance.h
Source/AbyssDiverUnderWorld/Character/UnderwaterCharacter.cpp
Source/AbyssDiverUnderWorld/Character/UnderwaterCharacter.h
Source/AbyssDiverUnderWorld/Physics/DefaultWaterPhysicsVolume.cpp
Source/AbyssDiverUnderWorld/Physics/DefaultWaterPhysicsVolume.h

---
- 지상 / 수중을 피직스 볼륨을 이용해서 처리
- ABP에 Slot을 추가
- 캐릭터 로깅 카테고리 추가
---
https://github.com/user-attachments/assets/8ef5e760-ad52-4b54-bc29-658d3a7639fb
---
---
맵을 기본으로 수중으로 설정하기 위해서는 Default Physics Volume을 Water로 설정해주시면 됩니다.
맵의 일부분을 지상 혹은 수중으로 설정하기 위해서는 Physics Volume을 설정해주시면 됩니다.
- 배치
- 설정
---

Add: 수중/지상 상태 구분, Anim Montage Slot 추가

---

Content/_AbyssDiver/Blueprints/Environmental_Factors/BP_Whale.uasset
Content/_AbyssDiver/Blueprints/Framework/BP_ADGameInstance.uasset
Content/_AbyssDiver/DataTable/SoundData/DT_BGM.uasset
Content/_AbyssDiver/DataTable/SoundData/DT_MonsterSFX.uasset
Content/_AbyssDiver/DataTable/SoundData/DT_SFX.uasset
Content/_AbyssDiver/DataTable/SoundData/DT_UISFX.uasset
Content/_AbyssDiver/Maps/Prototypes_Test/HSRTest/BP_SoundTest.uasset
Source/AbyssDiverUnderWorld/DataRow/SoundDataRow/BGMDataRow.h
Source/AbyssDiverUnderWorld/DataRow/SoundDataRow/MonsterSFXDataRow.h
Source/AbyssDiverUnderWorld/DataRow/SoundDataRow/SFXDataRow.h
Source/AbyssDiverUnderWorld/DataRow/SoundDataRow/UISFXDataRow.h
Source/AbyssDiverUnderWorld/Framework/ADGameInstance.cpp
Source/AbyssDiverUnderWorld/Framework/ADGameInstance.h
Source/AbyssDiverUnderWorld/Shops/Shop.cpp
Source/AbyssDiverUnderWorld/Subsystems/SoundSubsystem.cpp
Source/AbyssDiverUnderWorld/Subsystems/SoundSubsystem.h

---
- 사운드 데이터를 관리함과 동시에 사운드 재생 및 풀링 담당
- 사운드 종류를 BGM, Monster, UI, 그 외로 나눔
- 다만 설정상으로는 BGM과 SFX 두 종류로 관리함
문서 참고
https://teamsparta.notion.site/1ff2dc3ef51480968733c09b161bb6d9
- Shop : Light를 Static에서 Stationary로 변경 - Static을 사용할 수 없다는 경고 메세지 때문..
- BP_Whale : 초기에는 Tick 비활성화, 이후 이벤트가 발동되면 Tick활성화 되도록 변경 - 대영님 피드백 반영
---
---

🎉 add 사운드 관리 기능 추가 : SoundSubsystem, DataTables, 및 기타

---

Source/AbyssDiverUnderWorld/Framework/ADInGameState.cpp
Source/AbyssDiverUnderWorld/Framework/ADInGameState.h
Source/AbyssDiverUnderWorld/Framework/ADPlayerState.h
Source/AbyssDiverUnderWorld/Subsystems/MissionSubsystem.cpp
Source/AbyssDiverUnderWorld/Subsystems/MissionSubsystem.h
Source/AbyssDiverUnderWorld/Subsystems/SoundSubsystem.cpp
Source/AbyssDiverUnderWorld/UI/MissionSelectWidget.cpp
Source/AbyssDiverUnderWorld/UI/MissionSelectWidget.h
Source/AbyssDiverUnderWorld/UI/SelectedMissionListWidget.cpp
Source/AbyssDiverUnderWorld/UI/SelectedMissionListWidget.h

---
- 미션용 FastArray에 변화 감지용 델리게이트 추가
- 미션용 FastArray Refresh 함수 생성
- 필요 없다고 판단한 함수, 프로퍼티 삭제 : GetSelectedMissions, SetSelectedMissions, SelectedMissions
- 미션이 선택되고 만들어진 후 UI Refresh
- PlayerState를 활용한 로직 삭제 - MissionSubsystem에서 담당하므로
- PlayerState를 활용한 로직 삭제 - MissionSubsystem에서 담당하므로
- Refresh 함수 : 미션 UI 리스트 갱신 및 델리게이트 바인딩
- SoundSubsystem : while 무한 반복문 대신 안전 장치 추가 - 최대 100회까지만 반복하도록
---

선택한 미션 UI에 표시 및 UI 동기화 완료 및 기타

---

Source/AbyssDiverUnderWorld/Gimmic/Spawn/Spawner/Monster/MonsterSpawner.cpp
Source/AbyssDiverUnderWorld/Gimmic/Spawn/Spawner/Monster/MonsterSpawner.h
Source/AbyssDiverUnderWorld/Gimmic/Spawn/Spawner/Ore/OreSpawner.cpp
Source/AbyssDiverUnderWorld/Gimmic/Spawn/Spawner/Ore/OreSpawner.h
Source/AbyssDiverUnderWorld/Gimmic/Spawn/Spawner/Serpmare/SerpmareSpawner.cpp
Source/AbyssDiverUnderWorld/Gimmic/Spawn/Spawner/Serpmare/SerpmareSpawner.h
Source/AbyssDiverUnderWorld/Interactable/OtherActors/EventTriggers/EventTrigger.cpp
Source/AbyssDiverUnderWorld/Interactable/OtherActors/MissionSelectors/MissionSelector.cpp
Source/AbyssDiverUnderWorld/Shops/Shop.cpp

---
- 원인 : SpawnPoint를 찾는 과정과 Spawn하는 순서가 에디터와 반대여서 발생
- 둘다 Beginplay에서 일어났기 때문에 에디터에서는 GetSpawnPoint먼저 일어나고 이후 Spawn을 호출해서 정상이었으나
- 패키징시에는 순서가 반대여서 스폰이 되지 않음.
- 해결 : 더 빠른 시점에 호출되는 PostInitializeComponents로 로직 옮김
- PostInitializeComponents에 안전 코드 추가
---

🐛 bugfix 스포너들 버그 해결 및 기타

---

Content/_AbyssDiver/Blueprints/Environmental_Factors/BP_EnterDetectionVolume.uasset
Content/_AbyssDiver/Blueprints/UI/UI/WBP_PlayerStatusWidget.uasset
Content/_AbyssDiver/Maps/Prototypes_Test/YWC/TestMap.umap
Source/AbyssDiverUnderWorld/Character/PlayerComponent/PlayerHUDComponent.cpp
Source/AbyssDiverUnderWorld/Character/PlayerComponent/PlayerHUDComponent.h
Source/AbyssDiverUnderWorld/Framework/ADInGameMode.cpp
Source/AbyssDiverUnderWorld/Framework/ADInGameState.cpp
Source/AbyssDiverUnderWorld/Framework/ADInGameState.h
Source/AbyssDiverUnderWorld/Interactable/OtherActors/ADDrone.cpp
Source/AbyssDiverUnderWorld/UI/PlayerStatusWidget.cpp
Source/AbyssDiverUnderWorld/UI/PlayerStatusWidget.h

---
- 잠수정에 들어오면 위젯 끄는 용도
- 나침반의 목표물 위젯 켜고 끄는 기능 추가
- BP_EnterDetectionVolume을 잠수정 내부에 설치
- 레벨이 끝나면 다시 목표물 위젯 보이게 설정
- PlayerStatusWidget BlueprintReadOnly로 변경
- 나침반에 띄울 목적지 타겟을 설정
- 목적지 타겟 설정 변수 및 함수
- 페이즈 넘어걸 때마다 목적지 바꿈
---

✨ update  페이즈 전부 완료하면 나침반에 잠수정 위치 표시 🎉 add BP_EnterDetectionVolume

---

Content/_AbyssDiver/Blueprints/Monster/HorrorCreature/BT_HorrorCreature.uasset
Source/AbyssDiverUnderWorld/Character/PlayerComponent/LanternComponent.cpp
Source/AbyssDiverUnderWorld/Monster/BT/BTTask_InvestigateMoveTo.cpp
Source/AbyssDiverUnderWorld/Monster/BT/BTTask_InvestigateMoveTo.h
Source/AbyssDiverUnderWorld/Monster/HorrorCreature/HorrorCreature.cpp
Source/AbyssDiverUnderWorld/Monster/HorrorCreature/HorrorCreature.h

---
[[Fix] 랜턴을 끄거나 DetecteCollision에서 벗어나면 바로 Patrol 되는 문제 해결]
[[Update] 먹히고 나서 뱉었을 때 Player 안움직이던 문제 해결]
---

[Fix] 랜턴 껐을 때 Patrol로 바로 변경되는 문제 해결, Eject Victim 안움직이던 문제 해결

---

Content/_AbyssDiver/Blueprints/UI/MainMenu/WBP_PauseWidget.uasset
Source/AbyssDiverUnderWorld/Framework/ADCampGameMode.cpp
Source/AbyssDiverUnderWorld/Framework/ADInGameMode.cpp
Source/AbyssDiverUnderWorld/Interactable/Item/ADUseItem.cpp
Source/AbyssDiverUnderWorld/Interactable/Item/ADUseItem.h
Source/AbyssDiverUnderWorld/Shops/Shop.cpp
Source/AbyssDiverUnderWorld/Shops/Shop.h
Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopElementInfoWidget.cpp
Source/AbyssDiverUnderWorld/Shops/ShopWidgets/ShopElementInfoWidget.h
Source/AbyssDiverUnderWorld/Subsystems/MissionSubsystem.cpp
Source/AbyssDiverUnderWorld/Subsystems/MissionSubsystem.h

---
- 아이템마다 질량에 비례하여 날리는 힘 다르게 조절
- 날리는 방향 오차 부여하는 기능 추가
- 이전에 받았던 미션이 여전히 남아있는 현상 수정
- Pause로 게임을 나가고 게임을 재시작 할 시 인풋이 안먹히는 현상 해결
---

✨ update 상점 아이템 날리기 기능 개선 🐛 bugfix 미션 유지 현상, Pause후 게임 나갈시 인풋

---

Source/AbyssDiverUnderWorld/Projectile/ADSpearGunBullet.cpp

---
- 클라이언트에서는 적용 안되는 현상 수정
- 액터 자체 스케일을 1,1,1로 변경해서 클라이언트에도 적용됨.
---

🐛 bugfix 작살이 커지는 현상 수정

---

Content/_AbyssDiver/Maps/Prototypes_Test/DeepAbyss.umap

---
- 2, 3페이즈의 Serpmare Spawner의 영역이 겹쳐있어서 하나의 스폰 포인트를 각각의 스폰포인트로 인지하는 현상이 있었음
---

[BugFix] Serpmare 중복 스폰 버그 수정

---

Source/AbyssDiverUnderWorld/Interactable/Item/Component/EquipUseComponent.cpp
Source/AbyssDiverUnderWorld/Subsystems/SoundSubsystem.cpp
Source/AbyssDiverUnderWorld/Subsystems/SoundSubsystem.h

---
- 인벤토리 아이템 쓸 때 장비아이템 좌클릭 사용이 같이 일어나는 현상 : bEnableClickEvents 체크하는 조건 추가
- 레벨 이동시 사운드 재생되는 현상 : 레벨이 파괴될 때 사운드 풀 초기화
---

🐛 bugfix 인벤토리 아이템 쓸 때 장비아이템 좌클릭 사용이 같이 일어나는 현상, 레벨 이동시 사운드 재생되는 현상

---

Source/AbyssDiverUnderWorld/Framework/ADCampGameMode.cpp
Source/AbyssDiverUnderWorld/Framework/ADCampGameMode.h
Source/AbyssDiverUnderWorld/Framework/ADGameInstance.cpp
Source/AbyssDiverUnderWorld/Framework/ADGameInstance.h
Source/AbyssDiverUnderWorld/Framework/ADInGameMode.cpp
Source/AbyssDiverUnderWorld/Framework/ADInGameMode.h
Source/AbyssDiverUnderWorld/Interactable/OtherActors/Portals/PortalToSubmarine.cpp
Source/AbyssDiverUnderWorld/Subsystems/SoundSubsystem.cpp

---
- NetCulling때문에 플레이어간 거리가 너무 멀 경우 결과창이 제대로 로드 되지 않는 현상 수정
- 결과창 뜨기 전에 동기화 강제하고 1초 후 결과창 띄움 ### 사운드 버그
- 여전히 간헐적으로 맵이 넘어갈 때 이전에 실행되었던 사운드가 한꺼번에 실행 되는 현상이 있었음
- 맵 이동시 모든 사운드를 정지시키고 이동함.
- PreLogin때 InGameMode일 경우 참여 막음
- PreLogin때 CampGameMode일 경우 4인이라면 참여를 막음
- 일부 로그 verbosity Log로 변경
---

🐛 bugfix 결과창 버그, 사운드 버그 ✨ update  인게임 중에는 참여 불가, 4인 초과 참여 불가 설정 및 기타

---

Source/AbyssDiverUnderWorld/Character/ADSpectatorPawn.cpp

---
BugFix: Host에서 랜턴이 캐릭터를 가리는 현상 수정
Host에서 게임 시작 시에 Spectate Pawn과 Character Pawn이 공존해서 관전 종료 시점이 적용되고 있던 오류 수정
현재 에디터에서 리슨 서버 실행이 안 되서 Guest에서의 확인은 못해 봤습니다.
---

BugFix: Host에서 랜턴이 캐릭터를 가리는 현상 수정

---

Content/_AbyssDiver/Blueprints/Framework/BP_ADPlayerController.uasset
Content/_AbyssDiver/Blueprints/UI/InGameUI/WBP_Radar2D.uasset
Content/_AbyssDiver/Blueprints/UI/InGameUI/WBP_RadarReturn.uasset
Content/_AbyssDiver/Images/M_SciFi_Octopuse_Body_Skin1.uasset
Content/_AbyssDiver/Materials/RadarMaterials/M_Basic_Glow2D.uasset
Content/_AbyssDiver/Materials/RadarMaterials/M_Fresnel_Glow2D.uasset
Content/_AbyssDiver/Materials/RadarMaterials/M_Fresnel_Glow2D_Circle.uasset
Source/AbyssDiverUnderWorld/Character/PlayerComponent/PlayerHUDComponent.cpp
Source/AbyssDiverUnderWorld/Character/PlayerComponent/PlayerHUDComponent.h
Source/AbyssDiverUnderWorld/Character/PlayerComponent/UnderwaterEffectComponent.cpp
Source/AbyssDiverUnderWorld/Character/UnderwaterCharacter.cpp
Source/AbyssDiverUnderWorld/Character/UnderwaterCharacter.h
Source/AbyssDiverUnderWorld/Character/UnitBase.cpp
Source/AbyssDiverUnderWorld/Character/UnitBase.h
Source/AbyssDiverUnderWorld/Framework/ADPlayerController.cpp
Source/AbyssDiverUnderWorld/Framework/ADPlayerController.h
Source/AbyssDiverUnderWorld/Interactable/Item/ADOreRock.cpp
Source/AbyssDiverUnderWorld/Interactable/Item/ADOreRock.h
Source/AbyssDiverUnderWorld/Interactable/OtherActors/Radars/Radar2DComponent.cpp
Source/AbyssDiverUnderWorld/Interactable/OtherActors/Radars/Radar2DComponent.h
Source/AbyssDiverUnderWorld/Interactable/OtherActors/Radars/RadarReturn2DComponent.cpp
Source/AbyssDiverUnderWorld/Interactable/OtherActors/Radars/RadarReturn2DComponent.h
Source/AbyssDiverUnderWorld/UI/RadarWidgets/Radar2DWidget.cpp
Source/AbyssDiverUnderWorld/UI/RadarWidgets/Radar2DWidget.h
Source/AbyssDiverUnderWorld/UI/RadarWidgets/RadarReturnWidget.cpp
Source/AbyssDiverUnderWorld/UI/RadarWidgets/RadarReturnWidget.h

---
- 모든 RadarReturn2DComponent 관리
- 플레이어에게 유요한 리턴(레이더 범위 안) 제공
- 레이더의 대상이 되는 리턴 2d 버전
- bAlwaysDisplay : true이면 레이더에 항상 표시
- bAlwaysIgnore : true이면 레이더에서 항상 무시, bAlwaysDisplay 무효
- 레이더를 표시하는 위젯
- 레이더 리턴을 표시하는 위젯
- Radar2DWidget 생성 및 관리
- 컴파일 안되서 GameplayStatics헤더 추가
- Radar2DComponent 추가
- 기존 레이더 로직은 지우지 않았음. 레이더 입력 부분만 주석 처리 해둠.
- RadarReturn2DComponent 추가
- 레이더 활성화 함수 추가
- 블루프린트에서 PlayerHUDComponent에 WBP_Radar2D 클래스를 등록해줌.
- RadarReturn2DComponent 추가, 중립으로 설정
---
- 레이더 AddToViweport 때마다 조기화 해줘서 해결
- 플레이어 레이더에 항상 표시

🎉 add Radar 2D

---

Content/_AbyssDiver/Maps/Prototypes_Test/TutorialPool.umap
Source/AbyssDiverUnderWorld/Framework/ADTutorialGameMode.cpp
Source/AbyssDiverUnderWorld/Framework/ADTutorialGameMode.h
Source/AbyssDiverUnderWorld/Interactable/OtherActors/Radars/RadarReturn2DComponent.h
Source/AbyssDiverUnderWorld/Tutorial/TutorialManager.cpp
Source/AbyssDiverUnderWorld/Tutorial/TutorialManager.h

---
**튜토리얼 액터 등장 시점 조정**
- HandlePhase_Radar에 있던 관련 로직을 HandlePhase_Looting 함수로 이전하여, 'Looting' 단계의 목표와 액터의 등장을 일치시켰습니다
**게이지 미션 시작 조건 추가**
- 출력이 완료되기 전까지 게이지 관련 상호작용이 작동하지 않도록 막았습니다
**튜토리얼 시작 방식 변경 (트리거 → 타이머)**
- ATutorialTriggerZone 액터와 관련 로직을 모두 제거했습니다. 대신 **AADTutorialGameMode**의 StartPlay 함수에 2초짜리 타이머를 추가하여, 레벨 시작 후 2초가 지나면 첫 튜토리얼 단계(AdvanceTutorialPhase)가 자동으로 호출되도록 수정했습니다
---
---
---

튜토리얼 시작 자동화 및 진행 이벤트 조정

---

Content/_AbyssDiver/Animations/Monster/GolbleFish/AM_GobleFish_MeleeAttack_1.uasset
Content/_AbyssDiver/Animations/Monster/GolbleFish/AM_GobleFish_MeleeAttack_2.uasset
Content/_AbyssDiver/Blueprints/Boss/Blowfish/AIC_EnhancedBlowfish.uasset
Content/_AbyssDiver/Blueprints/Boss/Blowfish/AIC_EnhancedBlowfish_Lagacy.uasset
Content/_AbyssDiver/Blueprints/Boss/Blowfish/BB_Blowfish.uasset
Content/_AbyssDiver/Blueprints/Boss/Blowfish/BT_Blowfish.uasset
Content/_AbyssDiver/Blueprints/Boss/Blowfish/BT_Blowfish_Lagacy.uasset
Content/_AbyssDiver/Blueprints/Monster/GobleFish/BP_GobleFish.uasset
Content/_AbyssDiver/Blueprints/Monster/GobleFish/BT_GobleFish.uasset
Content/_AbyssDiver/Maps/Prototypes_Test/HSRTest/HSR_Test2.umap
Source/AbyssDiverUnderWorld/Monster/AnimNotify/AnimNotify_MonsterDefaultAttack.cpp
Source/AbyssDiverUnderWorld/Monster/BT/Commons/BTTask_SimpleChasePlayer.cpp
Source/AbyssDiverUnderWorld/Monster/Boss/Blowfish/Blowfish.cpp
Source/AbyssDiverUnderWorld/Monster/Boss/Boss.cpp
Source/AbyssDiverUnderWorld/Monster/Boss/Boss.h
Source/AbyssDiverUnderWorld/Monster/GobleFish/GobleFish.cpp
Source/AbyssDiverUnderWorld/Monster/GobleFish/GobleFish.h
Source/AbyssDiverUnderWorld/Monster/Monster.cpp

---
- AIC_EnhancedBlowfish : 부모를 MonsterAIController로 변경
- BB_Blowfish, BT_Blowfish, BP_GobleFish, BT_GobleFish : MonsterState기반 재설계
- UCapsuleComponent -> UShapeComponent (범용성)
- 해초사이에 숨을 때 로직 추가
- Attack함수 Monster 것으로 사용
- 폭발로 사망시 OnDeath 호출
- 폭발 데미지는 서버에서만 처리
- 공격 로직 Blowfish와 동일하게 콜리전 기반으로 변경
- Beginplay - Overlap 콜백 바인딩
- 생성자 : AM에 쓰일 태그 추가
- AnimNotify_MonsterDefaultAttack : 특정 타이밍에 공격 콜리전 활성화
- AM_GobleFish_MeleeAttack_1, AM_GobleFish_MeleeAttack_2 : AnimNotify_MonsterDefaultAttack 추가
- NotifyLightExposure : 플레이어가 숨은 상태이면 감지하지 않음
- Attack : 이미 어택 몽타주가 플레이 중이면 실행하지 않음
- ApplyPhysicsSimulation : 필요 없는 로직 주석
---

✨ update Blowfish, GobleFish BT 수정 및 기타, ♻️ refactor Boss, Blowfish, GobleFish, Monster

---

Content/TentacleEyes/Blueprints/BP_TentacleEye.uasset
Content/TentacleEyes/Meshes/Skeletal/SK_TentacleEye_Thick.uasset
Content/TentacleEyes/Meshes/Skeletal/SK_TentacleEye_Thin.uasset
Content/_AbyssDiver/Blueprints/Monster/EyeStalker/BP_EyeStalker.uasset
Content/_AbyssDiver/Maps/Prototypes_Test/HSRTest/HSR_Test2.umap
Source/AbyssDiverUnderWorld/Monster/EyeStalker/EyeStalker.cpp
Source/AbyssDiverUnderWorld/Monster/EyeStalker/EyeStalker.h
Source/AbyssDiverUnderWorld/Monster/Limadon/Limadon.cpp
Source/AbyssDiverUnderWorld/Monster/Limadon/Limadon.h
Source/AbyssDiverUnderWorld/Monster/Monster.cpp
Source/AbyssDiverUnderWorld/Monster/Monster.h
Source/AbyssDiverUnderWorld/Monster/Serpmare/Serpmare.cpp
Source/AbyssDiverUnderWorld/Monster/Serpmare/Serpmare.h
Source/AbyssDiverUnderWorld/Projectile/ADShotgunBullet.cpp

---
- 눈꺼풀 안 움직이는 현상 수정
- EyeStalker를 배치한 각도에 따라 응시 방향이 비정상적으로 변하는 현상 수정
- EyeStalker 피격 모션 : 데미지를 받으면 잠시 움츠러드는 효과 추가
- Monster 넉백 함수 추가
- BP_EyeStalker : 피격시 움즈러드는 효과 추가
- BP_TentacleEye : 타겟 응시 방향 로직 수정
- SK_TentacleEye_Thick, SK_TentacleEye_Thin : 눈꺼풀 Morph Target 복원
- EyeStalker : 데미지를 받을 때 호출되는 블루프린트 전용 이벤트 추가, 샷건에 넉백 당하지 않도록 override
- Limadon, Serpmare : 샷건에 넉백 당하지 않도록 override
- Monster : 자기 자신을 해당 방향에 특정 힘으로 넉백 시키는 함수 추가
- ADShotgunBullet : Monster 넉백 함수를 대신 사용해서 넉백시킴
---

🐛 bugfix EyeStalker 눈꺼풀, 응시 방향 ✨ update EyeStalker 피격 모션, 몬스터 넉백 기능
